# SPDX-License-Identifier: ice License 1.0
development: true
logger:
  encoder: console
  level: debug
cmd/heimdall-identity-io:
  host: localhost:8001
  version: local
  api-key:
   - bogus
   - bogus2
  requiredAppVersions:
    android: 9.9.9
    ios: 9.9.9
  assetLinks: '[]'
  appleAppSiteAssociation: '{
  "applinks": {
    "apps": [],
    "details": [
      {
        "appID": "bogus",
        "paths": [
          "*"
        ]
      }
    ]
  },
  "webcredentials": {
    "apps": [
      "bogus"
    ]
  }
}'
  defaultEndpointTimeout: 60s
  httpServer:
    port: 8001
    certPath: cmd/heimdall-identity-io/.testdata/localhost.crt
    keyPath: cmd/heimdall-identity-io/.testdata/localhost.key

cmd/heimdall-asset-data-syncer:
  version: local
  defaultEndpointTimeout: 60s
  httpServer:
    port: 8888
    certPath: cmd/heimdall-identity-io/.testdata/localhost.crt
    keyPath: cmd/heimdall-identity-io/.testdata/localhost.key
accounts:
  delegated_relying_party:
    auth:
      issuer: auth.dfns.ninja
    refreshToken:
      secret: bogus
      issuer: ION/local
      expirationTime: 24h
    ton:
      global-config-url: https://ton-blockchain.github.io/testnet-global.config.json
    ion:
      global-config-url: https://cdn.ice.io/testnet/global.config.json
    testnet: true
    allowedApplications:
      ap-bogus:
        name: Bogus
        origin: https://bogus.com
        rpId: bogus.com
    #baseUrl: https://bogus.example
    #webhookUrl:
    #appId: bogus
    #webFEAppId: bogus
    #serviceKey: bogus-key
    #credentialPrivateKey: bogus
    #credentialId: bogus
  fromEmailAddress: no-reply@ice.io
  fromEmailName: ice
  wintr/email:
    credentials:
      #apiKey: bogus
  wintr/sms:
    #messageServiceSIDs:
    #  th: MG12234
    #  ge: MG43211
    credentials:
      #user: bogus
      #password: bogus
  wintr/totp:
    issuer: ION
  emailExpiration: 15m
  smsExpiration: 15m
  userSignatureExpiration: 1h
  max2FACount: 2
  device-identification:
    #apiKey: bogus
    #proxySecret: bogus
    region: eu
    requestExpirationTime: 15m
    suspectThreshold: 999
    allowedUrls:
      - "com.android.bogus"
    allowedSdks:
      android: 2.9.0
    allowedClientApiKeys:
    #  - bogus
  defaultCoinsInWalletView:
    - ice
    - binancecoin
    - bitcoin
    - ethereum
    - solana
    - the-open-network
    - dogecoin
    - litecoin
    - stellar
    - tron
    - ripple
    - tezos
    - matic-network
    - polkadot
    - optimism
    - cardano
    - algorand
    - kusama
    - avalanche-2
    - kaspa
    - arbitrum
    - sonic-2
    - aptos

  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5437/heimdall
    primaryFallbackURLs:
      - postgresql://root:pass@localhost:5437/heimdall
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5437/heimdall
  privateKey: 97da572f75c23bff475bc48cd3ff193a0681e82907fb97d0a2d44ec1f0fb88b1b88d40e358e8264a3b9ca2a6abc0ba7bd2035d1647af7acdb211f4a3dccab44e
coins:
  testnet: true
  defaultSyncFrequency: 12h
  syncTokensDataFrequency: 24h
  syncFrequency:
    the-open-network: 10s
  fees:
    ton:
      slow:
        maxPriorityFee: 325000003
        maxFee: 325000091
        waitTime: 100000
      standard:
        maxPriorityFee: 325000003
        maxFee: 325000091
        waitTime: 200000
      fast:
        maxPriorityFee: 325000003
        maxFee: 325000091
        waitTime: 200000
    tontestnet:
      slow:
        maxPriorityFee: 325000003
        maxFee: 325000091
        waitTime: 100000
      standard:
        maxPriorityFee: 325000003
        maxFee: 325000091
        waitTime: 200000
      fast:
        maxPriorityFee: 325000003
        maxFee: 325000091
        waitTime: 200000
    ion:
      slow:
        maxPriorityFee: 225000003
        maxFee: 225000091
        waitTime: 100000
      standard:
        maxPriorityFee: 225000003
        maxFee: 225000091
        waitTime: 100000
      fast:
        maxPriorityFee: 225000003
        maxFee: 225000091
        waitTime: 100000
    iontestnet:
      slow:
        maxPriorityFee: 225000003
        maxFee: 225000091
        waitTime: 100000
      standard:
        maxPriorityFee: 225000003
        maxFee: 225000091
        waitTime: 100000
      fast:
        maxPriorityFee: 225000003
        maxFee: 225000091
        waitTime: 100000
    arbitrumone:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    arbitrumsepolia:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    avalanchec:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    avalanchecfuji:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    base:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    basesepolia:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    bsc:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    bsctestnet:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    ethereum:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    ethereumsepolia:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    fantomopera:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    fantomtestnet:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    optimism:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    optimismsepolia:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    polygon:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    polygonamoy:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
  coin-gecko:
    #api-key: bogus
    base-url: https://pro-api.coingecko.com
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5437/heimdall
    primaryFallbackURLs:
     - postgresql://root:pass@localhost:5437/heimdall
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5437/heimdall
nfts:
  coin-gecko:
    #api-key: bogus
    base-url: https://pro-api.coingecko.com
hashtagstatistics:
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5437/heimdall
    primaryFallbackURLs:
      - postgresql://root:pass@localhost:5437/heimdall
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5437/heimdall
nft-content:
  indexer:
    ion: https://api.testnet.ice.io/
  profileUriBaseUrl: https://example.com
  htmlPreviewBaseURL: https://example.com
  contentUriBaseUrl: https://example.com
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5437/heimdall
    primaryFallbackURLs:
      - postgresql://root:pass@localhost:5437/heimdall
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5437/heimdall
following:
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5437/heimdall
    primaryFallbackURLs:
      - postgresql://root:pass@localhost:5437/heimdall
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5437/heimdall
relay-management:
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5437/heimdall
    primaryFallbackURLs:
      - postgresql://root:pass@localhost:5437/heimdall
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5437/heimdall
apps-runtime:
  ion-app:
    _version: 3
    interestedThreshold: 0.5
    notInterestedCategoryChance: 0.3
    notInterestedSubcategoryChance: 0.2
    concurrentRequests: 3
    concurrentBigFileUploadChunks: 10
    followingReqMaxAge: 432000000
    followingCacheMaxAge: 432000000
    topMaxAge: 259200000
    trendingMaxAge: 86400000
    exploreMaxAge: 43200000
    repostThrottleDelay: 10800000
    concurrentMediaDownloadsLimit: 3
    excludeUnclassifiedFromExplore: true
    allowNewRegistrations: true
    enableEarlyAccessRegistrations: false
    maxEarlyAccessRegistrationsAllowedPerEmail: 3