# SPDX-License-Identifier: ice License 1.0

logger:
  encoder: console
  level: debug
cmd/heimdall:
  host: localhost:1444
  version: local
  defaultEndpointTimeout: 30s
  proxyDfnsEndpoints:
    - method: POST
      endpoint: "/auth/registration/delegated"
      tag: Login
    - method: POST
      endpoint: "/auth/registration/enduser"
      tag: Login
    - method: POST
      endpoint: "/auth/login/init"
      tag: Login
    - method: POST
      endpoint: "/auth/login"
      tag: Login
    - method: POST
      endpoint: "/auth/login/delegated"
      tag: Login
    - method: PUT
      endpoint: "/auth/logout"
      tag: Login
    - method: PUT
      endpoint: "/auth/recover/user"
      tag: Recovery
    - method: POST
      endpoint: "/wallets"
      tag: Wallets
    - method: POST
      endpoint: "/wallets/:walletId/delegate"
      tag: Wallets
    - method: GET
      endpoint: "/wallets/:walletId"
      tag: Wallets
    - method: GET
      endpoint: "/wallets"
      tag: Wallets
    - method: GET
      endpoint: "/wallets/:walletId/assets"
      tag: Wallets
    - method: GET
      endpoint: "/wallets/:walletId/nfts"
      tag: Wallets
    - method: GET
      endpoint: "/wallets/:walletId/history"
      tag: Wallets
    - method: PUT
      endpoint: "/wallets/:walletId/tags"
      tag: Wallets
    - method: POST
      endpoint: "/wallets/:walletId/transfers"
      tag: Wallets
    - method: POST
      endpoint: "/wallets/:walletId/transactions"
      tag: Wallets
    - method: GET
      endpoint: "/wallets/:walletId/transactions"
      tag: Wallets
    - method: POST
      endpoint: "/wallets/:walletId/signatures"
      tag: Wallets
  httpServer:
    port: 1444
    certPath: cmd/heimdall/.testdata/localhost.crt
    keyPath: cmd/heimdall/.testdata/localhost.key
accounts:
  dfns:
    baseURL: https://api.dfns.ninja/
    appId: bogus
    serviceKey: bogus-key
    credentialPrivateKey: bogus
    credentialId: bogus
  fromEmailAddress: no-reply@ice.io
  fromEmailName: ice
  wintr/email:
    credentials:
      #apiKey: bogus
  wintr/sms:
    credentials:
      #user: bogus
      #password: bogus
  wintr/totp:
    issuer: ION
  emailExpiration: 15h
  smsExpiration: 15m
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5437/heimdall
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5437/heimdall

