# SPDX-License-Identifier: ice License 1.0
development: true
logger:
  encoder: console
  level: debug
cmd/heimdall-identity-io:
  host: localhost:8001
  version: local
  api-key:
   - bogus
   - bogus2
  requiredAppVersions:
    android: 9.9.9
    ios: 9.9.9
  tokenizedCommunities:
    bondingCurveSmartContractAddress: 0x1E602c717B6b1343303E77E9DBfe45B37cf01144
    addressVersion: 6
    abiVersion: 6
  communityTokenAPIKey: dev-api-key
  supportedSwapTokens:
    version: 1
    tokens:
      - network: ion
        address: 0x2c73996BaBF1a06c2C057177353293f7cA0907c8
  multiswap:
    version: 1
    pancakeSwapWbnbAddress: 0xae13d989dac2f0debff460ac112a837c89baa7cd
    pancakeSwapIonTokenAddress: 0x2c73996babf1a06c2c057177353293f7ca0907c8
    pancakeSwapSwapRouterAddress: 0x1b81D678ffb9C0263b24A97847620C99d213eB14
    pancakeSwapQuoterV2Address: 0xbC203d7f83677c7ed3F7acEc959963E7F4ECC5C2
    pancakeSwapFeeTier: 500
  assetLinks: '[]'
  appleAppSiteAssociation: '{
  "applinks": {
    "apps": [],
    "details": [
      {
        "appID": "bogus",
        "paths": [
          "*"
        ]
      }
    ]
  },
  "webcredentials": {
    "apps": [
      "bogus"
    ]
  }
}'
  defaultEndpointTimeout: 60s
  httpServer:
    port: 8001
    certPath: cmd/heimdall-identity-io/.testdata/localhost.crt
    keyPath: cmd/heimdall-identity-io/.testdata/localhost.key

cmd/heimdall-asset-data-syncer:
  version: local
  defaultEndpointTimeout: 60s
  httpServer:
    port: 8888
    certPath: cmd/heimdall-identity-io/.testdata/localhost.crt
    keyPath: cmd/heimdall-identity-io/.testdata/localhost.key
cmd/heimdall-token-analytics:
  version: local
  defaultEndpointTimeout: 60s
  httpServer:
    port: 8888
    certPath: cmd/heimdall-identity-io/.testdata/localhost.crt
    keyPath: cmd/heimdall-identity-io/.testdata/localhost.key
accounts:
  transactionValidationFeeSlippage: 0.05
  delegated_relying_party:
    auth:
      issuer: auth.dfns.ninja
    refreshToken:
      secret: bogus
      issuer: ION/local
      expirationTime: 24h
    ton:
      global-config-url: https://ton-blockchain.github.io/testnet-global.config.json
    ion:
      global-config-url: https://cdn.ice.io/testnet/global.config.json
    testnet: true
    allowedApplications:
      ap-bogus:
        name: Bogus
        origin: https://bogus.com
        rpId: bogus.com
    #baseUrl: https://bogus.example
    #webhookUrl:
    #appId: bogus
    #webFEAppId: bogus
    #serviceKey: bogus-key
    #credentialPrivateKey: bogus
    #credentialId: bogus
  fromEmailAddress: no-reply@ice.io
  fromEmailName: ice
  wintr/email:
    credentials:
      #apiKey: bogus
  wintr/sms:
    #messageServiceSIDs:
    #  th: MG12234
    #  ge: MG43211
    credentials:
      #user: bogus
      #password: bogus
  wintr/totp:
    issuer: ION
  emailExpiration: 15m
  smsExpiration: 15m
  userSignatureExpiration: 1h
  max2FACount: 2
  device-identification:
    #apiKey: bogus
    #proxySecret: bogus
    region: eu
    requestExpirationTime: 15m
    suspectThreshold: 999
    allowedUrls:
      - "com.android.bogus"
    allowedSdks:
      android: 2.9.0
    allowedClientApiKeys:
    #  - bogus
  defaultCoinsInWalletView:
    - ion
    - ice
    - binancecoin
    - bitcoin
    - ethereum
    - solana
    - the-open-network
    - dogecoin
    - litecoin
    - stellar
    - tron
    - ripple
    - tezos
    - matic-network
    - polkadot
    - optimism
    - cardano
    - algorand
    - kusama
    - avalanche-2
    - kaspa
    - arbitrum
    - sonic-2
    - aptos

  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5437/heimdall
    primaryFallbackURLs:
      - postgresql://root:pass@localhost:5437/heimdall
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5437/heimdall
  identityKeypairs:
    - 97da572f75c23bff475bc48cd3ff193a0681e82907fb97d0a2d44ec1f0fb88b1b88d40e358e8264a3b9ca2a6abc0ba7bd2035d1647af7acdb211f4a3dccab44e
    - 0ba58ed6a830bed3239137dde811db6e905973c519636c4f06b5b4fbc0f7fac52663afe3b90183f3c894191bba6ede27851c39ffbfdecade2bcda30b67ced4a4
coins:
  testnet: true
  defaultSyncFrequency: 12h
  syncTokensDataFrequency: 24h
  syncFrequency:
    the-open-network: 10s
  fees:
    ton:
      slow:
        maxPriorityFee: 325000003
        maxFee: 325000091
        waitTime: 100000
      standard:
        maxPriorityFee: 325000003
        maxFee: 325000091
        waitTime: 200000
      fast:
        maxPriorityFee: 325000003
        maxFee: 325000091
        waitTime: 200000
    tontestnet:
      slow:
        maxPriorityFee: 325000003
        maxFee: 325000091
        waitTime: 100000
      standard:
        maxPriorityFee: 325000003
        maxFee: 325000091
        waitTime: 200000
      fast:
        maxPriorityFee: 325000003
        maxFee: 325000091
        waitTime: 200000
    ion:
      slow:
        maxPriorityFee: 225000003
        maxFee: 225000091
        waitTime: 100000
      standard:
        maxPriorityFee: 225000003
        maxFee: 225000091
        waitTime: 100000
      fast:
        maxPriorityFee: 225000003
        maxFee: 225000091
        waitTime: 100000
    iontestnet:
      slow:
        maxPriorityFee: 225000003
        maxFee: 225000091
        waitTime: 100000
      standard:
        maxPriorityFee: 225000003
        maxFee: 225000091
        waitTime: 100000
      fast:
        maxPriorityFee: 225000003
        maxFee: 225000091
        waitTime: 100000
    arbitrumone:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    arbitrumsepolia:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    avalanchec:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    avalanchecfuji:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    base:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    basesepolia:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    bsc:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    bsctestnet:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    ethereum:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    ethereumsepolia:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    fantomopera:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    fantomtestnet:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    optimism:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    optimismsepolia:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    polygon:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    polygonamoy:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
  coin-gecko:
    #api-key: bogus
    base-url: https://pro-api.coingecko.com
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5437/heimdall
    primaryFallbackURLs:
     - postgresql://root:pass@localhost:5437/heimdall
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5437/heimdall
nfts:
  coin-gecko:
    #api-key: bogus
    base-url: https://pro-api.coingecko.com
hashtagstatistics:
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5437/heimdall
    primaryFallbackURLs:
      - postgresql://root:pass@localhost:5437/heimdall
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5437/heimdall
indexer:
  ion: https://api.testnet.ice.io/
nft-content:
  profileUriBaseUrl: https://example.com
  htmlPreviewBaseURL: https://example.com
  contentUriBaseUrl: https://example.com
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5437/heimdall
    primaryFallbackURLs:
      - postgresql://root:pass@localhost:5437/heimdall
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5437/heimdall
following:
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5437/heimdall
    primaryFallbackURLs:
      - postgresql://root:pass@localhost:5437/heimdall
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5437/heimdall
relay-management:
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5437/heimdall
    primaryFallbackURLs:
      - postgresql://root:pass@localhost:5437/heimdall
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5437/heimdall
apps-runtime:
  ion-app:
    _version: 3
    interestedThreshold: 0.5
    notInterestedCategoryChance: 0.3
    notInterestedSubcategoryChance: 0.2
    concurrentRequests: 3
    concurrentBigFileUploadChunks: 10
    followingReqMaxAge: 432000000
    followingCacheMaxAge: 432000000
    topMaxAge: 259200000
    trendingMaxAge: 86400000
    exploreMaxAge: 43200000
    tokenizedCommunitiesMaxAge: 25920000000
    repostThrottleDelay: 10800000
    concurrentMediaDownloadsLimit: 3
    excludeUnclassifiedFromExplore: true
    allowNewRegistrations: true
    enableEarlyAccessRegistrations: false
    maxEarlyAccessRegistrationsAllowedPerEmail: 3
    forYouOverflowMultiplier: 1.5
    nsfwBlockThreshold: 0.5
    langDetectScoreThreshold: 0.5
    cdnBaseUrl: https://cdn.example.com/bogus
    forYouSeenSkipsMultiplier: 1
    feeSponsorId: "dummy"
token-analytics:
  workers: 10
  batchSize: 2
  enableDummyGenerator: false
  bondingCurve:
    smartContractAddress: 0xF411faBcE1A441E5655db72419Ba2B0b95ec9fCC
    tokenFactorySmartContractAddress: 0x26dae540C37aD4190156D45eC1ddB32243Fa33d0
    burnAddress: 0x0000000000000000000000000000000000696f6e
    bondingCurveProgressUpdateFrequency: 500ms
    rpcEndpoints:
      - https://bogus.pro/bogus/
    createTokenDefaults:
      profile: #creator
        initialPrice: 583400000000000
        finalPrice: 9749900000000000
        bondingCurveAlgAddress: "0x2d8e40053dAf7e21C9bbDAdE293D9010ED2b5E13"
        emissionVolume: 1000000000000000000000000000
        feeSponsorAddress: "0x24c7ef0f468840620e13174e44f0cf10abba3425"
        feeSponsorId: "fs-01jea-99pmi-e7f8j0ofu8q15k9f"
      post: #content
        initialPrice: 16600000000000
        finalPrice: 10135800000000000
        bondingCurveAlgAddress: "0x074B22eb9C5b95EF14F7c3BDc4E47e847C8e8b77"
        emissionVolume: 1000000000000000000000000000
        feeSponsorAddress: "0x24c7ef0f468840620e13174e44f0cf10abba3425"
        feeSponsorId: "fs-01jea-99pmi-e7f8j0ofu8q15k9f"
      video: #content
        initialPrice: 16600000000000
        finalPrice: 10135800000000000
        bondingCurveAlgAddress: "0x074B22eb9C5b95EF14F7c3BDc4E47e847C8e8b77"
        emissionVolume: 1000000000000000000000000000
        feeSponsorAddress: "0x24c7ef0f468840620e13174e44f0cf10abba3425"
        feeSponsorId: "fs-01jea-99pmi-e7f8j0ofu8q15k9f"
      article: #content
        initialPrice: 16600000000000
        finalPrice: 10135800000000000
        bondingCurveAlgAddress: "0x074B22eb9C5b95EF14F7c3BDc4E47e847C8e8b77"
        emissionVolume: 1000000000000000000000000000
        feeSponsorAddress: "0x24c7ef0f468840620e13174e44f0cf10abba3425"
        feeSponsorId: "fs-01jea-99pmi-e7f8j0ofu8q15k9f"
      comment: #content
        initialPrice: 16600000000000
        finalPrice: 10135800000000000
        bondingCurveAlgAddress: "0x074B22eb9C5b95EF14F7c3BDc4E47e847C8e8b77"
        emissionVolume: 1000000000000000000000000000
        feeSponsorAddress: "0x24c7ef0f468840620e13174e44f0cf10abba3425"
        feeSponsorId: "fs-01jea-99pmi-e7f8j0ofu8q15k9f"
  riverQueue:
    queueName: heimdall_ta
    maxQueueWorkers: 100
    jobMaxTimeout: 30s
  llm:
    apiKey: dev-llm-api-key
    imageQuality: low
    maxRetries: 10
  cdn:
    accessKey: dev-cdn-access-key
    urlUpload: https://localhost:9000
    urlDownload: https://localhost:9000
    maxJobTimeout: 2m
  identityServiceUrl: https://localhost:8001
  identityServiceApiKey: dev-api-key
  ionTokenAddress: 0x2c73996BaBF1a06c2C057177353293f7cA0907c8
  questdb:
    writeUrl: http::addr=localhost:9000
    user: root
    password: pass
    read:
      runDDL: true
      skipSettingsVerification: true
      primaryURL: postgresql://root:pass@localhost:8812/qdb?ssl_mode=disable
      credentials:
        user: root
        password: pass
      replicaURLs:
        - postgresql://read-user:read-pass@localhost:8812/qdb?ssl_mode=disable
  wintr/connectors/storage/v3:
    url: redis://default:@localhost:6379
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5445/ingested_data
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5445/ingested_data
