# SPDX-License-Identifier: ice License 1.0
development: true
logger:
  encoder: console
  level: debug
cmd/heimdall-identity-io:
  host: localhost:8001
  version: local
  api-key:
   - bogus
   - bogus2
  requiredAppVersions:
    android: 9.9.9
    ios: 9.9.9
  assetLinks: '[]'
  appleAppSiteAssociation: '{
  "applinks": {
    "apps": [],
    "details": [
      {
        "appID": "bogus",
        "paths": [
          "*"
        ]
      }
    ]
  },
  "webcredentials": {
    "apps": [
      "bogus"
    ]
  }
}'
  defaultEndpointTimeout: 60s
  httpServer:
    port: 8001
    certPath: cmd/heimdall-identity-io/.testdata/localhost.crt
    keyPath: cmd/heimdall-identity-io/.testdata/localhost.key

cmd/heimdall-asset-data-syncer:
  version: local
  defaultEndpointTimeout: 60s
  httpServer:
    port: 8888
    certPath: cmd/heimdall-identity-io/.testdata/localhost.crt
    keyPath: cmd/heimdall-identity-io/.testdata/localhost.key

accounts:
  delegated_relying_party:
    auth:
      issuer: auth.dfns.ninja
    refreshToken:
      secret: bogus
      issuer: ION/local
      expirationTime: 24h
    ton:
      global-config-url: https://ton-blockchain.github.io/testnet-global.config.json
    ion:
      global-config-url: https://cdn.ice.io/testnet/global.config.json
    testnet: true
    allowedApplications:
      ap-bogus:
        name: Bogus
        origin: https://bogus.com
        rpId: bogus.com
    #baseUrl: https://bogus.example
    #webhookUrl:
    #appId: bogus
    #webFEAppId: bogus
    #serviceKey: bogus-key
    #credentialPrivateKey: bogus
    #credentialId: bogus
  fromEmailAddress: no-reply@ice.io
  fromEmailName: ice
  wintr/email:
    credentials:
      #apiKey: bogus
  wintr/sms:
    credentials:
      #user: bogus
      #password: bogus
  wintr/totp:
    issuer: ION
  emailExpiration: 15m
  smsExpiration: 15m
  userSignatureExpiration: 1h
  max2FACount: 2
  mockRelays:
    - wss://relay.nostr.band/
    - wss://relay1.nostr.band/
    - wss://relay3.nostr.band/
  relaysPerUser: 1
  defaultCoinsInWalletView:
    - ice
    - binancecoin
    - bitcoin
    - ethereum
    - solana
    - the-open-network
    - dogecoin
    - litecoin
    - stellar
    - tron
    - ripple
    - tezos
    - matic-network
    - polkadot
    - optimism
    - cardano
    - algorand
    - kusama
    - avalanche-2
    - kaspa
    - arbitrum
    - sonic-2
    - aptos

  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5437/heimdall
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5437/heimdall
  privateKey: 97da572f75c23bff475bc48cd3ff193a0681e82907fb97d0a2d44ec1f0fb88b1b88d40e358e8264a3b9ca2a6abc0ba7bd2035d1647af7acdb211f4a3dccab44e
  caCert: |
    -----BEGIN CERTIFICATE-----
    MIIDijCCAnKgAwIBAgIJAMeawIdSd6+8MA0GCSqGSIb3DQEBCwUAMCcxCzAJBgNV
    BAYTAlVTMRgwFgYDVQQDDA9FeGFtcGxlLVJvb3QtQ0EwHhcNMjIwMTA0MjEwNDE3
    WhcNMjQxMDI0MjEwNDE3WjBtMQswCQYDVQQGEwJVUzESMBAGA1UECAwJWW91clN0
    YXRlMREwDwYDVQQHDAhZb3VyQ2l0eTEdMBsGA1UECgwURXhhbXBsZS1DZXJ0aWZp
    Y2F0ZXMxGDAWBgNVBAMMD2xvY2FsaG9zdC5sb2NhbDCCASIwDQYJKoZIhvcNAQEB
    BQADggEPADCCAQoCggEBAONuA1zntIXbNaEvt/n+/Jisib/8Bjvfm2I9ENMq0TBH
    OGlbZgJ9ywiKsrxBYH/O2q6Dsxy9fL5cSfcMmAS0FXPrcXQx/pVNCgNWLEXZyPDk
    SzSR+tlPXzuryN2/jbWtgOZc73kfxQVBqUWbLyMiXaxMxVGHgpYMg0w68Ee62d2H
    AnA7c0YBllvggDRSaoDRJJZTc8DDGAHm9x5583zdxpCQh/EeV+zIjd2lAGF0ioYu
    PV69lwyrTnY/s7WG59nRYwYR50JvbI4G+5bbpf4q2W7Q0BVLqwSdMJfAfG43N5U/
    4Q1dfyJeXavFfQaZWJtEiVOU9TBiV3QQto0tI28R6J0CAwEAAaNzMHEwQQYDVR0j
    BDowOKErpCkwJzELMAkGA1UEBhMCVVMxGDAWBgNVBAMMD0V4YW1wbGUtUm9vdC1D
    QYIJANxKhfP/dJTMMAkGA1UdEwQCMAAwCwYDVR0PBAQDAgTwMBQGA1UdEQQNMAuC
    CWxvY2FsaG9zdDANBgkqhkiG9w0BAQsFAAOCAQEAjrUp0epptzaaTULvhrFdNJ6e
    2WAeJpYCxMXjms7P+B/ldyIirDqG/WEzpN64Z1gXJhtxnw7IGTsQ8eXqLmBDk045
    vHhVbRhjVGADc+EVwX6OzQ+WQEGZzNDPX7DBObLC1ZV5LcfUwQXyACmlARlYgXJN
    GZFDkijDcvY3/Hyq9NkV6VGYPKnzxaal3v3cYO8FXQHaOLnu+SLWknT56y2vTa5/
    H4CoX8nrts5Fa0NuOdoyNA1c7IdHjR/dy4g5IUZW+Sbhr1nNgkECBJvJ5QOWZ3M4
    4a8NroD0ikzQDaeS4Tpk54WnJLEjDgQe5fX9RMu9F2sbr+wP+gUTmHuhLg/Ptw==
    -----END CERTIFICATE-----
coins:
  testnet: true
  defaultSyncFrequency: 12h
  syncTokensDataFrequency: 24h
  syncFrequency:
    the-open-network: 10s
  fees:
    ton:
      slow:
        maxPriorityFee: 325000003
        maxFee: 325000091
        waitTime: 100000
      standard:
        maxPriorityFee: 325000003
        maxFee: 325000091
        waitTime: 200000
      fast:
        maxPriorityFee: 325000003
        maxFee: 325000091
        waitTime: 200000
    tontestnet:
      slow:
        maxPriorityFee: 325000003
        maxFee: 325000091
        waitTime: 100000
      standard:
        maxPriorityFee: 325000003
        maxFee: 325000091
        waitTime: 200000
      fast:
        maxPriorityFee: 325000003
        maxFee: 325000091
        waitTime: 200000
    ion:
      slow:
        maxPriorityFee: 225000003
        maxFee: 225000091
        waitTime: 100000
      standard:
        maxPriorityFee: 225000003
        maxFee: 225000091
        waitTime: 100000
      fast:
        maxPriorityFee: 225000003
        maxFee: 225000091
        waitTime: 100000
    iontestnet:
      slow:
        maxPriorityFee: 225000003
        maxFee: 225000091
        waitTime: 100000
      standard:
        maxPriorityFee: 225000003
        maxFee: 225000091
        waitTime: 100000
      fast:
        maxPriorityFee: 225000003
        maxFee: 225000091
        waitTime: 100000
    arbitrumone:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    arbitrumsepolia:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    avalanchec:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    avalanchecfuji:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    base:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    basesepolia:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    bsc:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    bsctestnet:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    ethereum:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    ethereumsepolia:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    fantomopera:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    fantomtestnet:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    optimism:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    optimismsepolia:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    polygon:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
    polygonamoy:
      gasUsedMultiplier: 22000
      slow:
        waitTime: 400000
      standard:
        waitTime: 100000
      fast:
        waitTime: 4000
  coin-gecko:
    #api-key: bogus
    base-url: https://pro-api.coingecko.com
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5437/heimdall
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5437/heimdall
nfts:
  coin-gecko:
    #api-key: bogus
    base-url: https://pro-api.coingecko.com
hashtagstatistics:
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5437/heimdall
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5437/heimdall
