# SPDX-License-Identifier: ice License 1.0

logger:
  encoder: console
  level: debug
cmd/heimdall:
  host: localhost:1444
  version: local
  defaultEndpointTimeout: 30s
  proxyDfnsEndpoints:
    - method: POST
      endpoint: "auth/registration/delegated"
    - method: POST
      endpoint: "auth/registration/enduser"
    - method: POST
      endpoint: "auth/login/init"
    - method: POST
      endpoint: "auth/login"
    - method: POST
      endpoint: "auth/login/delegated"
    - method: PUT
      endpoint: "auth/logout"
    - method: PUT
      endpoint: "auth/recover/user"
  httpServer:
    port: 1444
    certPath: cmd/heimdall/.testdata/localhost.crt
    keyPath: cmd/heimdall/.testdata/localhost.key
accounts:
  dfns:
    baseURL: https://api.dfns.ninja/
    appId: bogus
    serviceKey: bogus-key
    credentialPrivateKey: bogus
    credentialId: bogus
  fromEmailAddress: no-reply@ice.io
  fromEmailName: ice
  wintr/email:
    credentials:
      #apiKey: bogus
  wintr/totp:
    issuer: ION
  emailExpiration: 15h
  smsExpiration: 15m
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5437/heimdall
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5437/heimdall

