// SPDX-License-Identifier: ice License 1.0

package coingecko

var Networks = map[string]*Network{
	"Algorand": &Network{
		ID:                 "Algorand",
		CoinGeckoNetworkID: "algorand",
		CoinGeckoPlatform:  "algorand",
		DefaultDecimals:    6,
		SkipSyncTokens:     true,
		DisplayName:        "Algorand",
		ExplorerURL:        "https://explorer.bitquery.io/algorand/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/3/large/algorand_logo_mark_black.png?1706606710",
	},
	"AlgorandTestnet": &Network{
		ID:                 "AlgorandTestnet",
		CoinGeckoNetworkID: "algorand",
		CoinGeckoPlatform:  "algorand",
		IsTestnet:          true,
		DefaultDecimals:    6,
		SkipSyncTokens:     true,
		DisplayName:        "Algorand",
		ExplorerURL:        "https://explorer.bitquery.io/algorand_testnet/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/3/large/algorand_logo_mark_black.png?1706606710",
	},
	"ArbitrumOne": &Network{
		ID:                 "ArbitrumOne",
		CoinGeckoNetworkID: "arbitrum",
		CoinGeckoPlatform:  "arbitrum-one",
		DefaultDecimals:    18,
		DisplayName:        "Arbitrum One",
		ExplorerURL:        "https://arbiscan.com/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/33/large/AO_logomark.png?1706606717",
	},
	"ArbitrumSepolia": &Network{
		ID:                 "ArbitrumSepolia",
		CoinGeckoNetworkID: "arbitrum",
		CoinGeckoPlatform:  "arbitrum-one",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "Arbitrum One",
		ExplorerURL:        "https://sepolia.arbiscan.com/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/33/large/AO_logomark.png?1706606717",
	},
	"AptosTestnet": &Network{
		ID:                 "AptosTestnet",
		CoinGeckoNetworkID: "aptos",
		CoinGeckoPlatform:  "aptos",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "Aptos",
		ExplorerURL:        "https://explorer.aptoslabs.com/txn/{txHash}?network=testnet",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/116/large/aptos_round.png?1706606789",
	},
	"Aptos": &Network{
		ID:                 "Aptos",
		CoinGeckoNetworkID: "aptos",
		CoinGeckoPlatform:  "aptos",
		DefaultDecimals:    18,
		DisplayName:        "Aptos",
		ExplorerURL:        "https://explorer.aptoslabs.com/txn/{txHash}?network=mainnet",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/116/large/aptos_round.png?1706606789",
	},
	"AvalancheC": &Network{
		ID:                 "AvalancheC",
		CoinGeckoNetworkID: "avax",
		CoinGeckoPlatform:  "avalanche",
		DisplayName:        "Avalanche",
		DefaultDecimals:    18,
		ExplorerURL:        "https://subnets.avax.network/c-chain/block/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/12/large/avalanche.png?1706606775",
	},
	"AvalancheCFuji": &Network{
		ID:                 "AvalancheCFuji",
		CoinGeckoNetworkID: "avax",
		CoinGeckoPlatform:  "avalanche",
		IsTestnet:          true,
		DisplayName:        "Avalanche",
		DefaultDecimals:    18,
		ExplorerURL:        "https://subnets-test.avax.network/c-chain/block/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/12/large/avalanche.png?1706606775",
	},
	"Base": &Network{
		ID:                 "Base",
		CoinGeckoNetworkID: "base",
		CoinGeckoPlatform:  "base",
		DefaultDecimals:    18,
		DisplayName:        "Base",
		ExplorerURL:        "https://basescan.com/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/131/large/base-network.png?1720533039",
	},
	"BaseSepolia": &Network{
		ID:                 "BaseSepolia",
		CoinGeckoNetworkID: "base",
		CoinGeckoPlatform:  "base",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "Base",
		ExplorerURL:        "https://sepolia.basescan.com/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/131/large/base-network.png?1720533039",
	},
	"Bitcoin": &Network{
		ID:                 "Bitcoin",
		CoinGeckoNetworkID: "bitcoin",
		CoinGeckoPlatform:  "bitcoin",
		DisplayName:        "Bitcoin",
		DefaultDecimals:    9,
		ExplorerURL:        "https://mempool.space/tx/{txHash}",
		Image:              "https://assets.coingecko.com/coins/images/1/standard/bitcoin.png?1696501400",
	},
	"BitcoinTestnet3": &Network{
		ID:                 "BitcoinTestnet3",
		CoinGeckoNetworkID: "bitcoin",
		CoinGeckoPlatform:  "bitcoin",
		IsTestnet:          true,
		DisplayName:        "Bitcoin",
		DefaultDecimals:    9,
		ExplorerURL:        "https://mempool.space/testnet/tx/{txHash}",
		Image:              "https://assets.coingecko.com/coins/images/1/standard/bitcoin.png?1696501400",
	},
	"Bsc": &Network{
		ID:                 "Bsc",
		CoinGeckoNetworkID: "bsc",
		CoinGeckoPlatform:  "binance-smart-chain",
		DefaultDecimals:    18,
		DisplayName:        "BSC",
		ExplorerURL:        "https://bscscan.com/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/1/large/bnb_smart_chain.png?1706606721",
	},
	"BscTestnet": &Network{
		ID:                 "BscTestnet",
		CoinGeckoNetworkID: "bsc",
		CoinGeckoPlatform:  "binance-smart-chain",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "BSC",
		ExplorerURL:        "https://testnet.bscscan.com/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/1/large/bnb_smart_chain.png?1706606721",
	},
	"Cardano": &Network{
		ID:                 "Cardano",
		CoinGeckoNetworkID: "cardano",
		CoinGeckoPlatform:  "cardano",
		DefaultDecimals:    18,
		DisplayName:        "Cardano",
		ExplorerURL:        "https://cardanoscan.io/transaction/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/22/large/cardano.jpg?1706606486",
	},
	"CardanoPreprod": &Network{
		ID:                 "CardanoPreprod",
		CoinGeckoNetworkID: "cardano",
		CoinGeckoPlatform:  "cardano",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "Cardano",
		ExplorerURL:        "https://preprod.cardanoscan.io/transaction/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/22/large/cardano.jpg?1706606486",
	},
	"Dogecoin": &Network{
		ID:                 "Dogecoin",
		CoinGeckoNetworkID: "dogecoin",
		CoinGeckoPlatform:  "dogecoin",
		DefaultDecimals:    8,
		DisplayName:        "Dogecoin",
		SkipSyncTokens:     true,
		Image:              "https://assets.coingecko.com/coins/images/5/standard/dogecoin.png?1696501409",
	},
	"Ethereum": &Network{
		ID:                 "Ethereum",
		CoinGeckoNetworkID: "eth",
		CoinGeckoPlatform:  "ethereum",
		DefaultDecimals:    18,
		DisplayName:        "Ethereum",
		ExplorerURL:        "https://etherscan.io/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/279/large/ethereum.png?1706606803",
	},
	"EthereumSepolia": &Network{
		ID:                 "EthereumSepolia",
		CoinGeckoNetworkID: "eth",
		CoinGeckoPlatform:  "ethereum",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "Ethereum",
		ExplorerURL:        "https://sepolia.etherscan.io/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/279/large/ethereum.png?1706606803",
	},
	"FantomOpera": &Network{
		ID:                 "FantomOpera",
		CoinGeckoNetworkID: "ftm",
		CoinGeckoPlatform:  "fantom",
		DefaultDecimals:    18,
		DisplayName:        "Fantom",
		ExplorerURL:        "https://explorer.fantom.network/transactions/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/17/large/fantom.png?1706606773",
	},
	"FantomTestnet": &Network{
		ID:                 "FantomTestnet",
		CoinGeckoNetworkID: "ftm",
		CoinGeckoPlatform:  "fantom",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "Fantom",
		ExplorerURL:        "https://explorer.testnet.fantom.network/transactions/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/17/large/fantom.png?1706606773",
	},
	"ICP": &Network{
		ID:                 "ICP",
		CoinGeckoNetworkID: "icp",
		CoinGeckoPlatform:  "internet-computer",
		DefaultDecimals:    18,
		DisplayName:        "ICP",
		ExplorerURL:        "https://www.icpexplorer.org/#/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/165/large/01_ICP_Token_HEX_white__2x.png?1706606785",
	},
	"Kusama": &Network{
		ID:                 "Kusama",
		CoinGeckoNetworkID: "kusama",
		CoinGeckoPlatform:  "kusama",
		DefaultDecimals:    12,
		DisplayName:        "Kusama",
		ExplorerURL:        "https://kusama.subscan.io/extrinsic/{txHash}",
		Image:              "https://assets.coingecko.com/coins/images/9568/standard/m4zRhP5e_400x400.jpg?1696509648",
	},
	"Optimism": &Network{
		ID:                 "Optimism",
		CoinGeckoNetworkID: "optimism",
		CoinGeckoPlatform:  "optimistic-ethereum",
		DefaultDecimals:    18,
		DisplayName:        "Optimism",
		ExplorerURL:        "https://optimistic.etherscan.io/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/41/large/optimism.png?1706606778",
	},
	"OptimismSepolia": &Network{
		ID:                 "OptimismSepolia",
		CoinGeckoNetworkID: "optimism",
		CoinGeckoPlatform:  "optimistic-ethereum",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "Optimism",
		ExplorerURL:        "https://sepolia-optimism.etherscan.io/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/41/large/optimism.png?1706606778",
	},
	"SeiPacific1": &Network{
		ID:                 "SeiPacific1",
		CoinGeckoNetworkID: "sei-network",
		CoinGeckoPlatform:  "sei-network",
		DefaultDecimals:    18,
		DisplayName:        "Sei Network",
		ExplorerURL:        "https://www.seiscan.app/pacific-1/txs/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/148/large/Sei_Logo_-_Transparent.png?1706606762",
	},
	"SeiAtlantic2": &Network{
		ID:                 "SeiAtlantic2",
		CoinGeckoNetworkID: "sei-network",
		CoinGeckoPlatform:  "sei-network",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "Sei Network",
		ExplorerURL:        "https://www.seiscan.app/atlantic-2/txs/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/148/large/Sei_Logo_-_Transparent.png?1706606762",
	},
	"Solana": &Network{
		ID:                 "Solana",
		CoinGeckoNetworkID: "solana",
		CoinGeckoPlatform:  "solana",
		DefaultDecimals:    9,
		DisplayName:        "Solana",
		ExplorerURL:        "https://solscan.io/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/5/large/solana.png?1706606708",
	},
	"SolanaDevnet": &Network{
		ID:                 "SolanaDevnet",
		CoinGeckoNetworkID: "solana",
		CoinGeckoPlatform:  "solana",
		IsTestnet:          true,
		DefaultDecimals:    9,
		DisplayName:        "Solana",
		ExplorerURL:        "https://solscan.io/tx/{txHash}?cluster=devnet",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/5/large/solana.png?1706606708",
	},
	"Polygon": &Network{
		ID:                 "Polygon",
		CoinGeckoNetworkID: "polygon_pos",
		CoinGeckoPlatform:  "polygon-pos",
		DefaultDecimals:    18,
		DisplayName:        "Polygon",
		ExplorerURL:        "https://polygonscan.com/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/15/large/polygon_pos.png?1706606645",
	},
	"PolygonAmoy": &Network{
		ID:                 "PolygonAmoy",
		CoinGeckoNetworkID: "polygon_pos",
		CoinGeckoPlatform:  "polygon-pos",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "Polygon",
		ExplorerURL:        "https://amoy.polygonscan.com/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/15/large/polygon_pos.png?1706606645",
	},
	"Ton": &Network{
		ID:                 "Ton",
		CoinGeckoNetworkID: "ton",
		CoinGeckoPlatform:  "the-open-network",
		DefaultDecimals:    9,
		DisplayName:        "TON",
		ExplorerURL:        "https://tonscan.org/address/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/142/large/tonblockchain.jpeg?1706606805",
	},
	"TonTestnet": &Network{
		ID:                 "TonTestnet",
		CoinGeckoNetworkID: "ton",
		CoinGeckoPlatform:  "the-open-network",
		IsTestnet:          true,
		DefaultDecimals:    9,
		DisplayName:        "TON",
		ExplorerURL:        "https://testnet.tonscan.org/address/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/142/large/tonblockchain.jpeg?1706606805",
	},
	"Ion": &Network{
		ID:                 "Ion",
		CoinGeckoNetworkID: "ion",
		CoinGeckoPlatform:  "TBD_ion",
		SkipSyncTokens:     true,
		DefaultDecimals:    9,
		DisplayName:        "ION",
		ExplorerURL:        "https://explorer.ice.io/address/{txHash}",
		Image:              "https://assets.coingecko.com/coins/images/34674/standard/ion-coingecko-200w.png?1714009819",
	},
	"IonTestnet": &Network{
		ID:                 "IonTestnet",
		CoinGeckoNetworkID: "ion",
		CoinGeckoPlatform:  "TBD_ion",
		SkipSyncTokens:     true,
		IsTestnet:          true,
		DefaultDecimals:    9,
		DisplayName:        "ION",
		ExplorerURL:        "https://explorer.testnet.ice.io/address/{txHash}",
		Image:              "https://assets.coingecko.com/coins/images/34674/standard/ion-coingecko-200w.png?1714009819",
	},
	"TronNile": &Network{
		ID:                 "TronNile",
		CoinGeckoNetworkID: "tron",
		CoinGeckoPlatform:  "tron",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "TRON",
		ExplorerURL:        "https://nile.tronscan.org/#/transaction/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/1094/large/TRON_LOGO.png?1706606652",
	},
	"Tron": &Network{
		ID:                 "Tron",
		CoinGeckoNetworkID: "tron",
		CoinGeckoPlatform:  "tron",
		DefaultDecimals:    18,
		DisplayName:        "TRON",
		ExplorerURL:        "https://tronscan.org/#/transaction/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/1094/large/TRON_LOGO.png?1706606652",
	},
	"XrpLedger": &Network{
		ID:                 "XrpLedger",
		CoinGeckoNetworkID: "xrp",
		CoinGeckoPlatform:  "xrp",
		DefaultDecimals:    6,
		SkipSyncTokens:     true,
		DisplayName:        "XRP Ledger",
		ExplorerURL:        "https://xrpscan.com/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/1094/large/TRON_LOGO.png?1706606652",
	},
	"XrpLedgerTestnet": &Network{
		ID:                 "XrpLedgerTestnet",
		CoinGeckoNetworkID: "xrp",
		CoinGeckoPlatform:  "xrp",
		IsTestnet:          true,
		DefaultDecimals:    6,
		SkipSyncTokens:     true,
		DisplayName:        "XRP Ledger",
		ExplorerURL:        "https://testnet.xrpl.org/transactions/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/1094/large/TRON_LOGO.png?1706606652",
	},
	"Litecoin": &Network{
		ID:                 "Litecoin",
		CoinGeckoNetworkID: "litecoin",
		CoinGeckoPlatform:  "litecoin",
		DefaultDecimals:    8,
		SkipSyncTokens:     true,
		DisplayName:        "Litecoin",
		ExplorerURL:        "https://blockchair.com/litecoin/transaction/{txHash}",
		Image:              "https://assets.coingecko.com/coins/images/2/standard/litecoin.png?1696501400",
	},
	"Tezos": &Network{
		ID:                 "Tezos",
		CoinGeckoNetworkID: "tezos",
		CoinGeckoPlatform:  "tezos",
		DefaultDecimals:    6,
		SkipSyncTokens:     true,
		DisplayName:        "Tezos",
		ExplorerURL:        "https://tzkt.io/{txHash}",
		Image:              "https://assets.coingecko.com/coins/images/976/standard/Tezos-logo.png?1696502091",
	},
	"TezosGhostnet": &Network{
		ID:                 "TezosGhostnet",
		CoinGeckoNetworkID: "tezos",
		CoinGeckoPlatform:  "tezos",
		IsTestnet:          true,
		DefaultDecimals:    6,
		SkipSyncTokens:     true,
		DisplayName:        "Tezos",
		ExplorerURL:        "https://ghostnet.tzkt.io/{txHash}",
		Image:              "https://assets.coingecko.com/coins/images/976/standard/Tezos-logo.png?1696502091",
	},
	"StellarTestnet": &Network{
		ID:                 "StellarTestnet",
		CoinGeckoNetworkID: "stellar",
		CoinGeckoPlatform:  "stellar",
		IsTestnet:          true,
		DefaultDecimals:    7,
		SkipSyncTokens:     true,
		DisplayName:        "Stellar",
		ExplorerURL:        "https://stellar.expert/explorer/testnet/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/100/large/stellar.jpeg?1708492494",
	},
	"Stellar": &Network{
		ID:                 "Stellar",
		CoinGeckoNetworkID: "stellar",
		CoinGeckoPlatform:  "stellar",
		DefaultDecimals:    7,
		DisplayName:        "Stellar",
		SkipSyncTokens:     true,
		ExplorerURL:        "https://stellar.expert/explorer/public/tx/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/100/large/stellar.jpeg?1708492494",
	},
	"Kaspa": &Network{
		ID:                 "Kaspa",
		CoinGeckoNetworkID: "kaspa",
		CoinGeckoPlatform:  "kasplex",
		DefaultDecimals:    8,
		SkipSyncTokens:     true,
		DisplayName:        "Kaspa",
		ExplorerURL:        "https://explorer.kaspa.org/txs/{txHash}",
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/22172/large/kasplex-2.png?1727064572",
	},
	"Polkadot": &Network{
		ID:                 "Polkadot",
		CoinGeckoNetworkID: "polkadot",
		CoinGeckoPlatform:  "polkadot",
		DefaultDecimals:    16,
		DisplayName:        "Polkadot",
		ExplorerURL:        "https://subscan.io/extrinsic/{txHash}",
		SkipSyncTokens:     true,
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/12171/large/polkadot.jpeg?1706606400",
	},
	"Westend": &Network{
		ID:                 "Westend",
		CoinGeckoNetworkID: "polkadot",
		CoinGeckoPlatform:  "polkadot",
		IsTestnet:          true,
		DefaultDecimals:    16,
		DisplayName:        "Polkadot",
		ExplorerURL:        "https://westend.subscan.io/extrinsic/{txHash}",
		SkipSyncTokens:     true,
		Image:              "https://coin-images.coingecko.com/asset_platforms/images/12171/large/polkadot.jpeg?1706606400",
	},
}
