// SPDX-License-Identifier: ice License 1.0

package coingecko

var networks = map[string]*Network{
	"Algorand": &Network{
		ID:                 "Algorand",
		CoinGeckoNetworkID: "algorand",
		CoinGeckoPlatform:  "algorand",
		DefaultDecimals:    6,
		SkipSyncTokens:     true,
		DisplayName:        "Algorand",
		ExplorerURL:        "https://explorer.bitquery.io/algorand/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_algorand.svg",
		Tier:               1,
	},
	"AlgorandTestnet": &Network{
		ID:                 "AlgorandTestnet",
		CoinGeckoNetworkID: "algorand",
		CoinGeckoPlatform:  "algorand",
		IsTestnet:          true,
		DefaultDecimals:    6,
		SkipSyncTokens:     true,
		DisplayName:        "Algorand",
		ExplorerURL:        "https://explorer.bitquery.io/algorand_testnet/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_algorand.svg",
		Tier:               1,
	},
	"ArbitrumOne": &Network{
		ID:                 "ArbitrumOne",
		CoinGeckoNetworkID: "arbitrum",
		CoinGeckoPlatform:  "arbitrum-one",
		DefaultDecimals:    18,
		DisplayName:        "Arbitrum One",
		ExplorerURL:        "https://arbiscan.com/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_arbitrumone.svg",
		Tier:               1,
	},
	"ArbitrumSepolia": &Network{
		ID:                 "ArbitrumSepolia",
		CoinGeckoNetworkID: "arbitrum",
		CoinGeckoPlatform:  "arbitrum-one",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "Arbitrum One",
		ExplorerURL:        "https://sepolia.arbiscan.com/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_arbitrumone.svg",
		Tier:               1,
	},
	"AptosTestnet": &Network{
		ID:                 "AptosTestnet",
		CoinGeckoNetworkID: "aptos",
		CoinGeckoPlatform:  "aptos",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "Aptos",
		ExplorerURL:        "https://explorer.aptoslabs.com/txn/{txHash}?network=testnet",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_aptos.svg",
		Tier:               1,
	},
	"Aptos": &Network{
		ID:                 "Aptos",
		CoinGeckoNetworkID: "aptos",
		CoinGeckoPlatform:  "aptos",
		DefaultDecimals:    18,
		DisplayName:        "Aptos",
		ExplorerURL:        "https://explorer.aptoslabs.com/txn/{txHash}?network=mainnet",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_aptos.svg",
		Tier:               1,
	},
	"AvalancheC": &Network{
		ID:                 "AvalancheC",
		CoinGeckoNetworkID: "avax",
		CoinGeckoPlatform:  "avalanche",
		DisplayName:        "Avalanche",
		DefaultDecimals:    18,
		ExplorerURL:        "https://subnets.avax.network/c-chain/block/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_avalance.svg",
		Tier:               1,
	},
	"AvalancheCFuji": &Network{
		ID:                 "AvalancheCFuji",
		CoinGeckoNetworkID: "avax",
		CoinGeckoPlatform:  "avalanche",
		IsTestnet:          true,
		DisplayName:        "Avalanche",
		DefaultDecimals:    18,
		ExplorerURL:        "https://subnets-test.avax.network/c-chain/block/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_avalance.svg",
		Tier:               1,
	},
	"Base": &Network{
		ID:                 "Base",
		CoinGeckoNetworkID: "base",
		CoinGeckoPlatform:  "base",
		DefaultDecimals:    18,
		DisplayName:        "Base",
		ExplorerURL:        "https://basescan.com/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_base.svg",
		Tier:               1,
	},
	"BaseSepolia": &Network{
		ID:                 "BaseSepolia",
		CoinGeckoNetworkID: "base",
		CoinGeckoPlatform:  "base",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "Base",
		ExplorerURL:        "https://sepolia.basescan.com/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_base.svg",
		Tier:               1,
	},
	"Bitcoin": &Network{
		ID:                 "Bitcoin",
		CoinGeckoNetworkID: "bitcoin",
		CoinGeckoPlatform:  "bitcoin",
		DisplayName:        "Bitcoin",
		DefaultDecimals:    9,
		ExplorerURL:        "https://mempool.space/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_btc.svg",
		Tier:               1,
	},
	"BitcoinTestnet3": &Network{
		ID:                 "BitcoinTestnet3",
		CoinGeckoNetworkID: "bitcoin",
		CoinGeckoPlatform:  "bitcoin",
		IsTestnet:          true,
		DisplayName:        "Bitcoin",
		DefaultDecimals:    9,
		ExplorerURL:        "https://mempool.space/testnet/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_btc.svg",
		Tier:               1,
	},
	"Berachain": &Network{
		ID:                 "Berachain",
		CoinGeckoNetworkID: "berachain",
		CoinGeckoPlatform:  "berachain",
		IsTestnet:          false,
		DisplayName:        "Berachain",
		DefaultDecimals:    18,
		ExplorerURL:        "https://berascan.com/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_berachain.svg",
		Tier:               1,
	},
	"BerachainBepolia": &Network{
		ID:                 "BerachainBepolia",
		CoinGeckoNetworkID: "berachain",
		CoinGeckoPlatform:  "berachain",
		IsTestnet:          true,
		DisplayName:        "Berachain",
		DefaultDecimals:    18,
		ExplorerURL:        "https://testnet.berascan.com/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_berachain.svg",
		Tier:               1,
	},
	"Bsc": &Network{
		ID:                 "Bsc",
		CoinGeckoNetworkID: "bsc",
		CoinGeckoPlatform:  "binance-smart-chain",
		DefaultDecimals:    18,
		DisplayName:        "BSC",
		ExplorerURL:        "https://bscscan.com/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_binance.svg",
		Tier:               1,
	},
	"BscTestnet": &Network{
		ID:                 "BscTestnet",
		CoinGeckoNetworkID: "bsc",
		CoinGeckoPlatform:  "binance-smart-chain",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "BSC",
		ExplorerURL:        "https://testnet.bscscan.com/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_binance.svg",
		Tier:               1,
	},
	"Cardano": &Network{
		ID:                 "Cardano",
		CoinGeckoNetworkID: "cardano",
		CoinGeckoPlatform:  "cardano",
		DefaultDecimals:    6,
		DisplayName:        "Cardano",
		ExplorerURL:        "https://cardanoscan.io/transaction/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_cardano.svg",
		Tier:               2,
	},
	"CardanoPreprod": &Network{
		ID:                 "CardanoPreprod",
		CoinGeckoNetworkID: "cardano",
		CoinGeckoPlatform:  "cardano",
		IsTestnet:          true,
		DefaultDecimals:    6,
		DisplayName:        "Cardano",
		ExplorerURL:        "https://preprod.cardanoscan.io/transaction/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_cardano.svg",
		Tier:               2,
	},
	"Dogecoin": &Network{
		ID:                 "Dogecoin",
		CoinGeckoNetworkID: "dogecoin",
		CoinGeckoPlatform:  "dogecoin",
		DefaultDecimals:    8,
		DisplayName:        "Dogecoin",
		SkipSyncTokens:     true,
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_dogecoin.svg",
		Tier:               1,
	},
	"Ethereum": &Network{
		ID:                 "Ethereum",
		CoinGeckoNetworkID: "eth",
		CoinGeckoPlatform:  "ethereum",
		DefaultDecimals:    18,
		DisplayName:        "Ethereum",
		ExplorerURL:        "https://etherscan.io/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_eth.svg",
		Tier:               1,
		PrioritizedCoins:   []string{"ethereum"},
	},
	"EthereumSepolia": &Network{
		ID:                 "EthereumSepolia",
		CoinGeckoNetworkID: "eth",
		CoinGeckoPlatform:  "ethereum",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "Ethereum",
		ExplorerURL:        "https://sepolia.etherscan.io/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_eth.svg",
		Tier:               1,
		PrioritizedCoins:   []string{"ethereum"},
	},
	"FantomOpera": &Network{
		ID:                 "FantomOpera",
		CoinGeckoNetworkID: "ftm",
		CoinGeckoPlatform:  "fantom",
		DefaultDecimals:    18,
		DisplayName:        "Fantom",
		ExplorerURL:        "https://explorer.fantom.network/transactions/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_fantom.svg",
		Tier:               1,
	},
	"FantomTestnet": &Network{
		ID:                 "FantomTestnet",
		CoinGeckoNetworkID: "ftm",
		CoinGeckoPlatform:  "fantom",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "Fantom",
		ExplorerURL:        "https://explorer.testnet.fantom.network/transactions/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_fantom.svg",
		Tier:               1,
	},
	"ICP": &Network{
		ID:                 "ICP",
		CoinGeckoNetworkID: "icp",
		CoinGeckoPlatform:  "internet-computer",
		DefaultDecimals:    18,
		DisplayName:        "ICP",
		ExplorerURL:        "https://www.icpexplorer.org/#/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_icp.svg",
		Tier:               1,
	},
	"Kusama": &Network{
		ID:                 "Kusama",
		CoinGeckoNetworkID: "kusama",
		CoinGeckoPlatform:  "kusama",
		DefaultDecimals:    12,
		DisplayName:        "Kusama",
		ExplorerURL:        "https://kusama.subscan.io/extrinsic/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_kusama.svg",
		Tier:               2,
	},
	"Optimism": &Network{
		ID:                 "Optimism",
		CoinGeckoNetworkID: "optimism",
		CoinGeckoPlatform:  "optimistic-ethereum",
		DefaultDecimals:    18,
		DisplayName:        "Optimism",
		ExplorerURL:        "https://optimistic.etherscan.io/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_optimism.svg",
		Tier:               1,
	},
	"OptimismSepolia": &Network{
		ID:                 "OptimismSepolia",
		CoinGeckoNetworkID: "optimism",
		CoinGeckoPlatform:  "optimistic-ethereum",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "Optimism",
		ExplorerURL:        "https://sepolia-optimism.etherscan.io/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_optimism.svg",
		Tier:               1,
	},
	"SeiPacific1": &Network{
		ID:                 "SeiPacific1",
		CoinGeckoNetworkID: "sei-network",
		CoinGeckoPlatform:  "sei-network",
		DefaultDecimals:    18,
		DisplayName:        "Sei Network",
		ExplorerURL:        "https://www.seiscan.app/pacific-1/txs/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_sei.svg",
		Tier:               1,
	},
	"SeiAtlantic2": &Network{
		ID:                 "SeiAtlantic2",
		CoinGeckoNetworkID: "sei-network",
		CoinGeckoPlatform:  "sei-network",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "Sei Network",
		ExplorerURL:        "https://www.seiscan.app/atlantic-2/txs/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_sei.svg",
		Tier:               1,
	},
	"Solana": &Network{
		ID:                 "Solana",
		CoinGeckoNetworkID: "solana",
		CoinGeckoPlatform:  "solana",
		DefaultDecimals:    9,
		DisplayName:        "Solana",
		ExplorerURL:        "https://solscan.io/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_solana.svg",
		Tier:               1,
	},
	"SolanaDevnet": &Network{
		ID:                 "SolanaDevnet",
		CoinGeckoNetworkID: "solana",
		CoinGeckoPlatform:  "solana",
		IsTestnet:          true,
		DefaultDecimals:    9,
		DisplayName:        "Solana",
		ExplorerURL:        "https://solscan.io/tx/{txHash}?cluster=devnet",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_solana.svg",
		Tier:               1,
	},
	"Polygon": &Network{
		ID:                 "Polygon",
		CoinGeckoNetworkID: "polygon_pos",
		CoinGeckoPlatform:  "polygon-pos",
		DefaultDecimals:    18,
		DisplayName:        "Polygon",
		ExplorerURL:        "https://polygonscan.com/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_matic.svg",
		Tier:               1,
	},
	"PolygonAmoy": &Network{
		ID:                 "PolygonAmoy",
		CoinGeckoNetworkID: "polygon_pos",
		CoinGeckoPlatform:  "polygon-pos",
		IsTestnet:          true,
		DefaultDecimals:    18,
		DisplayName:        "Polygon",
		ExplorerURL:        "https://amoy.polygonscan.com/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_matic.svg",
		Tier:               1,
	},
	"Ton": &Network{
		ID:                 "Ton",
		CoinGeckoNetworkID: "ton",
		CoinGeckoPlatform:  "the-open-network",
		DefaultDecimals:    9,
		DisplayName:        "TON",
		ExplorerURL:        "https://tonscan.org/address/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_ton.svg",
		Tier:               1,
	},
	"TonTestnet": &Network{
		ID:                 "TonTestnet",
		CoinGeckoNetworkID: "ton",
		CoinGeckoPlatform:  "the-open-network",
		IsTestnet:          true,
		DefaultDecimals:    9,
		DisplayName:        "TON",
		ExplorerURL:        "https://testnet.tonscan.org/address/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_ton.svg",
		Tier:               1,
	},
	"Ion": &Network{
		ID:                 "Ion",
		CoinGeckoNetworkID: "ion",
		CoinGeckoPlatform:  "TBD_ion",
		SkipSyncTokens:     true,
		DefaultDecimals:    9,
		DisplayName:        "ION",
		ExplorerURL:        "https://explorer.ice.io/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_ice.svg",
		Tier:               1,
	},
	"IonTestnet": &Network{
		ID:                 "IonTestnet",
		CoinGeckoNetworkID: "ion",
		CoinGeckoPlatform:  "TBD_ion",
		SkipSyncTokens:     true,
		IsTestnet:          true,
		DefaultDecimals:    9,
		DisplayName:        "ION",
		ExplorerURL:        "https://explorer.testnet.ice.io/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_ice.svg",
		Tier:               1,
	},
	"TronNile": &Network{
		ID:                 "TronNile",
		CoinGeckoNetworkID: "tron",
		CoinGeckoPlatform:  "tron",
		IsTestnet:          true,
		DefaultDecimals:    6,
		DisplayName:        "TRON",
		ExplorerURL:        "https://nile.tronscan.org/#/transaction/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_tron.svg",
		Tier:               1,
	},
	"Tron": &Network{
		ID:                 "Tron",
		CoinGeckoNetworkID: "tron",
		CoinGeckoPlatform:  "tron",
		DefaultDecimals:    6,
		DisplayName:        "TRON",
		ExplorerURL:        "https://tronscan.org/#/transaction/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_tron.svg",
		Tier:               1,
	},
	"XrpLedger": &Network{
		ID:                 "XrpLedger",
		CoinGeckoNetworkID: "xrp",
		CoinGeckoPlatform:  "xrp",
		DefaultDecimals:    6,
		SkipSyncTokens:     true,
		DisplayName:        "XRP Ledger",
		ExplorerURL:        "https://xrpscan.com/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_xrp.svg",
		Tier:               2,
	},
	"XrpLedgerTestnet": &Network{
		ID:                 "XrpLedgerTestnet",
		CoinGeckoNetworkID: "xrp",
		CoinGeckoPlatform:  "xrp",
		IsTestnet:          true,
		DefaultDecimals:    6,
		SkipSyncTokens:     true,
		DisplayName:        "XRP Ledger",
		ExplorerURL:        "https://testnet.xrpl.org/transactions/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_xrp.svg",
		Tier:               2,
	},
	"Litecoin": &Network{
		ID:                 "Litecoin",
		CoinGeckoNetworkID: "litecoin",
		CoinGeckoPlatform:  "litecoin",
		DefaultDecimals:    8,
		SkipSyncTokens:     true,
		DisplayName:        "Litecoin",
		ExplorerURL:        "https://blockchair.com/litecoin/transaction/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_ltc.svg",
		Tier:               1,
	},
	"Tezos": &Network{
		ID:                 "Tezos",
		CoinGeckoNetworkID: "tezos",
		CoinGeckoPlatform:  "tezos",
		DefaultDecimals:    6,
		SkipSyncTokens:     true,
		DisplayName:        "Tezos",
		ExplorerURL:        "https://tzkt.io/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_tezos.svg",
		Tier:               2,
	},
	"TezosGhostnet": &Network{
		ID:                 "TezosGhostnet",
		CoinGeckoNetworkID: "tezos",
		CoinGeckoPlatform:  "tezos",
		IsTestnet:          true,
		DefaultDecimals:    6,
		SkipSyncTokens:     true,
		DisplayName:        "Tezos",
		ExplorerURL:        "https://ghostnet.tzkt.io/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_tezos.svg",
		Tier:               2,
	},
	"StellarTestnet": &Network{
		ID:                 "StellarTestnet",
		CoinGeckoNetworkID: "stellar",
		CoinGeckoPlatform:  "stellar",
		IsTestnet:          true,
		DefaultDecimals:    7,
		SkipSyncTokens:     true,
		DisplayName:        "Stellar",
		ExplorerURL:        "https://stellar.expert/explorer/testnet/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_stellar.svg",
		Tier:               1,
	},
	"Stellar": &Network{
		ID:                 "Stellar",
		CoinGeckoNetworkID: "stellar",
		CoinGeckoPlatform:  "stellar",
		DefaultDecimals:    7,
		DisplayName:        "Stellar",
		SkipSyncTokens:     true,
		ExplorerURL:        "https://stellar.expert/explorer/public/tx/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_stellar.svg",
		Tier:               1,
	},
	"Kaspa": &Network{
		ID:                 "Kaspa",
		CoinGeckoNetworkID: "kaspa",
		CoinGeckoPlatform:  "kasplex",
		DefaultDecimals:    8,
		SkipSyncTokens:     true,
		DisplayName:        "Kaspa",
		ExplorerURL:        "https://explorer.kaspa.org/txs/{txHash}",
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_kaspa.svg",
		Tier:               1,
	},
	"Polkadot": &Network{
		ID:                 "Polkadot",
		CoinGeckoNetworkID: "polkadot",
		CoinGeckoPlatform:  "polkadot",
		DefaultDecimals:    12,
		DisplayName:        "Polkadot",
		ExplorerURL:        "https://subscan.io/extrinsic/{txHash}",
		SkipSyncTokens:     true,
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_polkadot.svg",
		Tier:               2,
	},
	"Westend": &Network{
		ID:                 "Westend",
		CoinGeckoNetworkID: "polkadot",
		CoinGeckoPlatform:  "polkadot",
		IsTestnet:          true,
		DefaultDecimals:    12,
		DisplayName:        "Polkadot",
		ExplorerURL:        "https://westend.subscan.io/extrinsic/{txHash}",
		SkipSyncTokens:     true,
		Image:              "https://cdn.ice.io/online+/assets/networks/wallet_polkadot.svg",
		Tier:               2,
	},
}
