// SPDX-License-Identifier: ice License 1.0

// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "ice.io",
            "url": "https://ice.io"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/community-token-analytics/{analyticsType}": {
            "get": {
                "description": "Returns aggregated analytics for community tokens.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "parameters": [
                    {
                        "enum": [
                            "global"
                        ],
                        "type": "string",
                        "description": "Analytics type",
                        "name": "analyticsType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "24h",
                            "7d",
                            "30d"
                        ],
                        "type": "string",
                        "description": "Time interval",
                        "name": "interval",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Analytics data",
                        "schema": {
                            "$ref": "#/definitions/main.GlobalTokenStatistics"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                }
            }
        },
        "/v1/community-tokens": {
            "get": {
                "description": "Returns community tokens information for the given Ion Connect addresses.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "External addresses of the tokens",
                        "name": "externalAddresses",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"0:holder123:\"",
                        "description": "Holder external address to get tokens by holder",
                        "name": "holder",
                        "in": "query"
                    },
                    {
                        "maximum": 10,
                        "minimum": 1,
                        "type": "integer",
                        "example": 3,
                        "description": "Number of top platform holders to include (1-10)",
                        "name": "includeTopPlatformHolders",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"bitcoin\"",
                        "description": "Search keyword for filtering tokens",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 10,
                        "description": "Number of items to return (requires keyword)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 0,
                        "description": "Number of items to skip (requires keyword)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns tokens list with X_Total_Holdings header when holder parameter is used",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tokenanalytics.CommunityToken"
                            }
                        },
                        "headers": {
                            "X_Total_Holdings": {
                                "type": "integer",
                                "description": "Total holdings amount for the specified holder (only present when holder parameter is provided)"
                            }
                        }
                    },
                    "400": {
                        "description": "if request parameters are invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1/community-tokens/suggest-creation-details": {
            "post": {
                "description": "Suggests token creation details (ticker, name, picture) based on content and creator information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "parameters": [
                    {
                        "description": "Content and creator information",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.SuggestCreationDetailsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.Response-main_SuggestCreationDetailsResponse"
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/server.Response-main_SuggestCreationDetailsResponse"
                        }
                    },
                    "400": {
                        "description": "if request body is invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1/community-tokens/{externalAddressOrViewType}": {
            "get": {
                "description": "Returns community tokens by view type. \"latest\" requires authentication; \"rewardsDistribution\" is public and requires referenceDate.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "parameters": [
                    {
                        "enum": [
                            "latest",
                            "rewardsDistribution"
                        ],
                        "type": "string",
                        "example": "\"latest\"",
                        "description": "View type",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "profile",
                            "post",
                            "video",
                            "article",
                            "anyPost",
                            "xcom"
                        ],
                        "type": "string",
                        "example": "\"profile\"",
                        "description": "Token type filter",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"bitcoin\"",
                        "description": "Search keyword",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"2025-01-03T16:00:00Z\"",
                        "description": "Reference date (required for rewardsDistribution)",
                        "name": "referenceDate",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 10,
                        "description": "Number of items to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 0,
                        "description": "Number of items to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tokenanalytics.CommunityToken"
                            }
                        }
                    },
                    "400": {
                        "description": "if required params are missing",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "403": {
                        "description": "if auth is required but missing (latest)",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1/community-tokens/{externalAddressOrViewType}/bondingCurveProgress": {
            "get": {
                "description": "Returns progress of bonding curve for the community token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0:9dbf3f196310fb4a1818f619a686b15e6ffa78d723e843973fcdc9125f15bc2f:\"",
                        "description": "External address of the token",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.BondingCurveProgress"
                        }
                    },
                    "400": {
                        "description": "if request parameters are invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1/community-tokens/{externalAddressOrViewType}/external-data": {
            "put": {
                "description": "Syncs external user and token information. At least one field must be provided. Requires authentication.\nSpecial case: when externalAddressOrViewType is \"twitterProfiles\", updates the logged-in user's profile.\nOtherwise, updates token information associated with the specified external address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token external address or 'twitterProfiles' for logged-in user profile update",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User and token information",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ExternalDataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Data synced successfully"
                    },
                    "400": {
                        "description": "if request body is invalid or all fields are empty",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "409": {
                        "description": "if duplicate data conflict occurs",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1/community-tokens/{externalAddressOrViewType}/latest-trades": {
            "get": {
                "description": "Returns trade history for a specific community token address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 10,
                        "description": "Number of items to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 0,
                        "description": "Number of items to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tokenanalytics.Trade"
                            }
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1/community-tokens/{externalAddressOrViewType}/ohlcv": {
            "get": {
                "description": "Get OHLCV (Open, High, Low, Close, Volume) data for a specific community token address (closed candles).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"1m\"",
                        "description": "Time interval",
                        "name": "interval",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"10\"",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"0\"",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tokenanalytics.OHLCV"
                            }
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1/community-tokens/{externalAddressOrViewType}/positions": {
            "get": {
                "description": "Returns positions for specific holders of a community token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0:9dbf3f196310fb4a1818f619a686b15e6ffa78d723e843973fcdc9125f15bc2f:\"",
                        "description": "External address of the token",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "example": "\"0:abc123:,0:def456:\"",
                        "description": "External addresses of holders",
                        "name": "externalHolderAddresses",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tokenanalytics.HolderPosition"
                            }
                        }
                    },
                    "400": {
                        "description": "if request parameters are invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1/community-tokens/{externalAddressOrViewType}/pricing": {
            "get": {
                "description": "Returns pricing for the community token (per 1 = 1e18wei base)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0:9dbf3f196310fb4a1818f619a686b15e6ffa78d723e843973fcdc9125f15bc2f:\"",
                        "description": "External address of the token",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"buy\"",
                        "description": "Buy or sell",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Amount of tokens to exchange (in wei)",
                        "name": "amount",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Amount of BNB to exchange (in wei)",
                        "name": "amountBNB",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "format": "float64",
                        "description": "Amount of USD to exchange (ex: 1.99)",
                        "name": "amountUSD",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.PriceResponse"
                        }
                    },
                    "400": {
                        "description": "if request parameters are invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1/community-tokens/{externalAddressOrViewType}/viewing-sessions": {
            "post": {
                "description": "Creates a new session view for community tokens analytics.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "parameters": [
                    {
                        "enum": [
                            "top",
                            "trending",
                            "bondingCurveProgress"
                        ],
                        "type": "string",
                        "example": "\"top\"",
                        "description": "View type",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "profile",
                            "post",
                            "video",
                            "article",
                            "anyPost",
                            "xcom"
                        ],
                        "type": "string",
                        "example": "\"profile\"",
                        "description": "Token type filter",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SessionViewCreateResponse"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1/community-tokens/{externalAddressOrViewType}/viewing-sessions/{viewingSessionId}": {
            "get": {
                "description": "Returns community tokens information for a specific viewing session.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "parameters": [
                    {
                        "enum": [
                            "top",
                            "trending",
                            "bondingCurveProgress"
                        ],
                        "type": "string",
                        "example": "\"top\"",
                        "description": "View type",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"550e8400-e29b-41d4-a716-446655440000\"",
                        "description": "Viewing session ID",
                        "name": "viewingSessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"bitcoin\"",
                        "description": "Search keyword",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 10,
                        "description": "Number of items to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 0,
                        "description": "Number of items to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tokenanalytics.CommunityToken"
                            }
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1sse/community-tokens": {
            "get": {
                "description": "Streams community tokens information for the given Ion Connect addresses.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "example": "0x1234...,0x5678...",
                        "description": "External addresses of the tokens",
                        "name": "externalAddresses",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 10,
                        "minimum": 1,
                        "type": "integer",
                        "example": 3,
                        "description": "Number of top platform holders to include (1-10)",
                        "name": "includeTopPlatformHolders",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.CommunityToken"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1sse/community-tokens/{externalAddressOrViewType}": {
            "get": {
                "description": "Streams community tokens information for the given type.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"latest\",\"featured\",\"top\",\"trending\",\"bondingCurveProgress\"",
                        "description": "View type (latest, featured, top, trending, or bondingCurveProgress)",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"550e8400-e29b-41d4-a716-446655440000\"",
                        "description": "Viewing session ID (required for top/trending/bondingCurveProgress)",
                        "name": "viewingSessionId",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "profile",
                            "post",
                            "video",
                            "article",
                            "anyPost",
                            "xcom"
                        ],
                        "type": "string",
                        "example": "\"profile\"",
                        "description": "Token type filter",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.CommunityToken"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1sse/community-tokens/{externalAddressOrViewType}/bondingCurveProgress": {
            "get": {
                "description": "Streams updates of bonding curve progress",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.BondingCurveProgress"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1sse/community-tokens/{externalAddressOrViewType}/latest-trades": {
            "get": {
                "description": "Streams latest trades for a specific community token address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.Trade"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1sse/community-tokens/{externalAddressOrViewType}/ohlcv": {
            "get": {
                "description": "Streams OHLCV (Open, High, Low, Close, Volume) data for a specific community token address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"1m\"",
                        "description": "Time interval",
                        "name": "interval",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.OHLCV"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1sse/community-tokens/{externalAddressOrViewType}/top-holders": {
            "get": {
                "description": "Streams top holders information for a specific community token address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 10,
                        "description": "Number of items to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.TopHolderPosition"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1sse/community-tokens/{externalAddressOrViewType}/trading-stats": {
            "get": {
                "description": "Streams trading statistics for a specific community token address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.TradeStats"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1ws/community-tokens": {
            "get": {
                "description": "Streams community tokens information for the given Ion Connect addresses.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "example": "0x1234...,0x5678...",
                        "description": "External addresses of the tokens",
                        "name": "externalAddresses",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 10,
                        "minimum": 1,
                        "type": "integer",
                        "example": 3,
                        "description": "Number of top platform holders to include (1-10)",
                        "name": "includeTopPlatformHolders",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.CommunityToken"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1ws/community-tokens/{externalAddressOrViewType}": {
            "get": {
                "description": "Streams community tokens information for the given type.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"latest\",\"featured\",\"top\",\"trending\",\"bondingCurveProgress\"",
                        "description": "View type (latest, featured, top, trending, or bondingCurveProgress)",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"550e8400-e29b-41d4-a716-446655440000\"",
                        "description": "Viewing session ID (required for top/trending/bondingCurveProgress)",
                        "name": "viewingSessionId",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "profile",
                            "post",
                            "video",
                            "article",
                            "anyPost",
                            "xcom"
                        ],
                        "type": "string",
                        "example": "\"profile\"",
                        "description": "Token type filter",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.CommunityToken"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1ws/community-tokens/{externalAddressOrViewType}/bondingCurveProgress": {
            "get": {
                "description": "Streams updates of bonding curve progress",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.BondingCurveProgress"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1ws/community-tokens/{externalAddressOrViewType}/latest-trades": {
            "get": {
                "description": "Streams latest trades for a specific community token address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.Trade"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1ws/community-tokens/{externalAddressOrViewType}/ohlcv": {
            "get": {
                "description": "Streams OHLCV (Open, High, Low, Close, Volume) data for a specific community token address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"1m\"",
                        "description": "Time interval",
                        "name": "interval",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.OHLCV"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1ws/community-tokens/{externalAddressOrViewType}/top-holders": {
            "get": {
                "description": "Streams top holders information for a specific community token address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 10,
                        "description": "Number of items to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.TopHolderPosition"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        },
        "/v1ws/community-tokens/{externalAddressOrViewType}/trading-stats": {
            "get": {
                "description": "Streams trading statistics for a specific community token address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.TradeStats"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    },
                    {
                        "XCom": []
                    }
                ]
            }
        }
    },
    "definitions": {
        "main.ExternalDataRequest": {
            "type": "object",
            "properties": {
                "postAuthorAvatar": {
                    "type": "string",
                    "example": "https://example.com/avatar.png"
                },
                "postAuthorDisplayName": {
                    "type": "string",
                    "example": "John Doe"
                },
                "postAuthorExternalAddress": {
                    "type": "string",
                    "example": "30023:431cbb22566b87c35ce6cffcca5593876cc64b9085d1355944c03d865540a95b:ionconnect.app"
                },
                "postAuthorUsername": {
                    "type": "string",
                    "example": "johndoe"
                },
                "postAuthorVerified": {
                    "type": "boolean",
                    "example": true
                },
                "tokenImageUrl": {
                    "type": "string",
                    "example": "https://example.com/token.png"
                },
                "userAvatar": {
                    "type": "string",
                    "example": "https://example.com/avatar.png"
                },
                "userBSCWalletAddress": {
                    "type": "string",
                    "example": "0x1234567890abcdef1234567890abcdef12345678"
                },
                "userDisplayName": {
                    "type": "string",
                    "example": "John Doe"
                },
                "userExternalAddress": {
                    "type": "string",
                    "example": "1234567890"
                },
                "userUsername": {
                    "type": "string",
                    "example": "johndoe"
                },
                "userVerified": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "main.GlobalTokenStatistics": {
            "type": "object",
            "properties": {
                "launched": {
                    "type": "integer"
                },
                "migrated": {
                    "type": "integer"
                },
                "volume": {
                    "type": "number"
                }
            }
        },
        "main.PriceResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "amountBNB": {
                    "type": "string"
                },
                "amountUSD": {
                    "type": "number"
                },
                "bondingCurveAlgAddress": {
                    "description": "Pricing model",
                    "type": "string"
                },
                "creatorTokenParams": {
                    "$ref": "#/definitions/tokenanalytics.StartTokenParams"
                },
                "emissionVolume": {
                    "type": "string"
                },
                "feeSponsorAddress": {
                    "type": "string"
                },
                "feeSponsorId": {
                    "type": "string"
                },
                "finalPrice": {
                    "type": "string"
                },
                "finalPriceUSD": {
                    "type": "number"
                },
                "initialPrice": {
                    "type": "string"
                },
                "initialPriceUSD": {
                    "type": "number"
                },
                "usdPriceBNB": {
                    "type": "number"
                },
                "usdPriceION": {
                    "type": "number"
                }
            }
        },
        "main.SessionViewCreateResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "ttl": {
                    "description": "Session TTL in seconds",
                    "type": "integer",
                    "example": 1800
                }
            }
        },
        "main.SuggestCreationDetailsRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "some post text"
                },
                "contentId": {
                    "type": "string",
                    "example": "external address of the content"
                },
                "contentImages": {
                    "description": "Base64-encoded images from the post.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "contentVideoFrames": {
                    "description": "Base64-encoded video frames.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "creator": {
                    "$ref": "#/definitions/tokenanalytics.CreationDetailsCreator"
                }
            }
        },
        "main.SuggestCreationDetailsResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Something even cooler"
                },
                "picture": {
                    "type": "string",
                    "example": "https://example.com/some_cool_pic.webp"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/tokenanalytics.TokenDetailsGenerationStatus"
                        }
                    ],
                    "example": "completed"
                },
                "ticker": {
                    "type": "string",
                    "example": "SOMETHING_COOL"
                }
            }
        },
        "server.Response-main_SuggestCreationDetailsResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "contentType": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/main.SuggestCreationDetailsResponse"
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "raw": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "int32"
                    }
                }
            }
        },
        "server.ResponseErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "SOMETHING_NOT_FOUND"
                },
                "error": {
                    "type": "string",
                    "example": "something is missing"
                }
            }
        },
        "tokenanalytics.Addresses": {
            "type": "object",
            "properties": {
                "blockchain": {
                    "type": "string"
                },
                "ionConnect": {
                    "type": "string"
                },
                "twitter": {
                    "type": "string"
                }
            }
        },
        "tokenanalytics.BondingCurveProgress": {
            "type": "object",
            "properties": {
                "bondingCurveAlgAddress": {
                    "description": "Pricing model",
                    "type": "string"
                },
                "currentAmount": {
                    "type": "string"
                },
                "currentAmountUSD": {
                    "type": "number"
                },
                "emissionVolume": {
                    "type": "string"
                },
                "feeSponsorAddress": {
                    "type": "string"
                },
                "feeSponsorId": {
                    "type": "string"
                },
                "finalPrice": {
                    "type": "string"
                },
                "finalPriceUSD": {
                    "type": "number"
                },
                "goalAmount": {
                    "type": "string"
                },
                "goalAmountUSD": {
                    "type": "number"
                },
                "initialPrice": {
                    "type": "string"
                },
                "initialPriceUSD": {
                    "type": "number"
                },
                "liquidityUSD": {
                    "type": "number"
                },
                "migrated": {
                    "type": "boolean"
                },
                "raisedAmount": {
                    "type": "string"
                }
            }
        },
        "tokenanalytics.CommunityToken": {
            "type": "object",
            "properties": {
                "addresses": {
                    "$ref": "#/definitions/tokenanalytics.Addresses"
                },
                "createdAt": {
                    "type": "string"
                },
                "creator": {
                    "$ref": "#/definitions/tokenanalytics.User"
                },
                "description": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "launcher": {
                    "$ref": "#/definitions/tokenanalytics.User"
                },
                "marketData": {
                    "$ref": "#/definitions/tokenanalytics.MarketData"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "tokenanalytics.CreationDetailsCreator": {
            "type": "object",
            "properties": {
                "bio": {
                    "type": "string",
                    "example": "Something"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "username": {
                    "type": "string",
                    "example": "jdoe"
                },
                "website": {
                    "type": "string",
                    "example": "https://some.website.example.com"
                }
            }
        },
        "tokenanalytics.CreatorTokenInfo": {
            "type": "object",
            "properties": {
                "addresses": {
                    "$ref": "#/definitions/tokenanalytics.Addresses"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "ticker": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "tokenanalytics.HolderPosition": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "amountUSD": {
                    "type": "number"
                },
                "holder": {
                    "$ref": "#/definitions/tokenanalytics.User"
                },
                "pnl": {
                    "type": "number"
                },
                "pnlPercentage": {
                    "type": "number"
                },
                "rank": {
                    "type": "integer"
                },
                "supplyShare": {
                    "type": "number"
                }
            }
        },
        "tokenanalytics.MarketData": {
            "type": "object",
            "properties": {
                "bondingCurveProgress": {
                    "$ref": "#/definitions/tokenanalytics.BondingCurveProgress"
                },
                "holders": {
                    "type": "integer"
                },
                "liquidityUSD": {
                    "type": "number"
                },
                "marketCap": {
                    "type": "number"
                },
                "platformHolders": {
                    "type": "integer"
                },
                "position": {
                    "$ref": "#/definitions/tokenanalytics.Position"
                },
                "priceUSD": {
                    "type": "number"
                },
                "supply": {
                    "type": "string"
                },
                "ticker": {
                    "type": "string"
                },
                "topPlatformHolders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tokenanalytics.HolderPosition"
                    }
                },
                "volume": {
                    "type": "number"
                }
            }
        },
        "tokenanalytics.OHLCV": {
            "type": "object",
            "properties": {
                "close": {
                    "type": "number"
                },
                "high": {
                    "type": "number"
                },
                "low": {
                    "type": "number"
                },
                "market_cap": {
                    "type": "number"
                },
                "open": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "integer"
                },
                "volume": {
                    "type": "number"
                }
            }
        },
        "tokenanalytics.Position": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "amountUSD": {
                    "type": "number"
                },
                "pnl": {
                    "type": "number"
                },
                "pnlPercentage": {
                    "type": "number"
                },
                "rank": {
                    "type": "integer"
                }
            }
        },
        "tokenanalytics.StartTokenParams": {
            "type": "object",
            "properties": {
                "bondingCurveAlgAddress": {
                    "description": "Pricing model",
                    "type": "string"
                },
                "emissionVolume": {
                    "type": "string"
                },
                "finalPrice": {
                    "type": "string"
                },
                "finalPriceUSD": {
                    "type": "number"
                },
                "initialPrice": {
                    "type": "string"
                },
                "initialPriceUSD": {
                    "type": "number"
                }
            }
        },
        "tokenanalytics.TokenDetailsGenerationStatus": {
            "type": "string",
            "enum": [
                "pending",
                "generating_ticker",
                "generating_picture",
                "uploading",
                "completed",
                "failed"
            ],
            "x-enum-varnames": [
                "TokenDetailsGenerationStatusPending",
                "TokenDetailsGenerationStatusGenerating",
                "TokenDetailsGenerationStatusGeneratingPicture",
                "TokenDetailsGenerationStatusUploading",
                "TokenDetailsGenerationStatusCompleted",
                "TokenDetailsGenerationStatusFailed"
            ]
        },
        "tokenanalytics.TopHolderPosition": {
            "type": "object",
            "properties": {
                "creator": {
                    "$ref": "#/definitions/tokenanalytics.User"
                },
                "position": {
                    "$ref": "#/definitions/tokenanalytics.HolderPosition"
                }
            }
        },
        "tokenanalytics.Trade": {
            "type": "object",
            "properties": {
                "creator": {
                    "$ref": "#/definitions/tokenanalytics.User"
                },
                "position": {
                    "$ref": "#/definitions/tokenanalytics.TradePosition"
                }
            }
        },
        "tokenanalytics.TradePosition": {
            "type": "object",
            "properties": {
                "addresses": {
                    "$ref": "#/definitions/tokenanalytics.Addresses"
                },
                "amount": {
                    "type": "string"
                },
                "amountUSD": {
                    "type": "number"
                },
                "balance": {
                    "type": "string"
                },
                "balanceUSD": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "holder": {
                    "$ref": "#/definitions/tokenanalytics.User"
                },
                "type": {
                    "$ref": "#/definitions/tokenanalytics.TradeType"
                }
            }
        },
        "tokenanalytics.TradeStats": {
            "type": "object",
            "properties": {
                "1h": {
                    "$ref": "#/definitions/tokenanalytics.TradeStatsAggregate"
                },
                "24h": {
                    "$ref": "#/definitions/tokenanalytics.TradeStatsAggregate"
                },
                "5m": {
                    "$ref": "#/definitions/tokenanalytics.TradeStatsAggregate"
                },
                "6h": {
                    "$ref": "#/definitions/tokenanalytics.TradeStatsAggregate"
                }
            }
        },
        "tokenanalytics.TradeStatsAggregate": {
            "type": "object",
            "properties": {
                "buysTotalAmountUSD": {
                    "type": "number"
                },
                "netBuy": {
                    "type": "number"
                },
                "numberOfBuys": {
                    "type": "integer"
                },
                "numberOfSells": {
                    "type": "integer"
                },
                "priceDiff": {
                    "type": "number"
                },
                "sellsTotalAmountUSD": {
                    "type": "number"
                },
                "volumeUSD": {
                    "type": "number"
                }
            }
        },
        "tokenanalytics.TradeType": {
            "type": "string",
            "enum": [
                "buy",
                "sell"
            ],
            "x-enum-varnames": [
                "TradeTypeBuy",
                "TradeTypeSell"
            ]
        },
        "tokenanalytics.User": {
            "type": "object",
            "properties": {
                "addresses": {
                    "$ref": "#/definitions/tokenanalytics.Addresses"
                },
                "avatar": {
                    "type": "string"
                },
                "display": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "$ref": "#/definitions/tokenanalytics.CreatorTokenInfo"
                },
                "verified": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "Nostr": {
            "description": "Type \"Nostr\" followed by a space and your Nostr NIP-42 compatible base64-encoded event.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "XCom": {
            "description": "Type \"X.com\" followed by a space and base64-encoded JSON with user info: {\"userId\":\"...\",\"userHandle\":\"...\",\"displayName\":\"...\",\"verified\":true}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "latest",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"https"},
	Title:            "Token Analytics Service API.",
	Description:      "This service provides analytics data for various tokens.\nURLs starting with /v1/sse return Server-Sent Events (SSE) for real-time updates.\nURLs starting with /v1/ws utilize WebSockets for bidirectional communication.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
