// SPDX-License-Identifier: ice License 1.0

// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "ice.io",
            "url": "https://ice.io"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/community-tokens": {
            "get": {
                "description": "Returns community tokens information for the given Ion Connect addresses.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "example": "0x1234...,0x5678...",
                        "description": "External addresses of the tokens",
                        "name": "externalAddresses",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 10,
                        "minimum": 1,
                        "type": "integer",
                        "example": 3,
                        "description": "Number of top holders to include (1-10)",
                        "name": "includeTopHolders",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tokenanalytics.CommunityToken"
                            }
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    }
                ]
            }
        },
        "/v1/community-tokens/{externalAddressOrViewType}": {
            "get": {
                "description": "Returns community tokens information for the given Ion Connect addresses.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"latest\"",
                        "description": "View type (latest)",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"bitcoin\"",
                        "description": "Search keyword",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 10,
                        "description": "Number of items to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 0,
                        "description": "Number of items to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tokenanalytics.CommunityToken"
                            }
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    }
                ]
            }
        },
        "/v1/community-tokens/{externalAddressOrViewType}/external-data": {
            "put": {
                "description": "Syncs external information for a community token (e.g., Twitter data scraping). Backend only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    }
                ]
            }
        },
        "/v1/community-tokens/{externalAddressOrViewType}/latest-trades": {
            "get": {
                "description": "Returns trade history for a specific community token address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 10,
                        "description": "Number of items to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 0,
                        "description": "Number of items to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tokenanalytics.Trade"
                            }
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    }
                ]
            }
        },
        "/v1/community-tokens/{externalAddressOrViewType}/viewing-sessions": {
            "post": {
                "description": "Creates a new session view for community tokens analytics.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"top\"",
                        "description": "View type (top, trending, or bondingCurveProgress)",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"profile\"",
                        "description": "Token type filter (profile, post, video, or article)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SessionViewCreateResponse"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    }
                ]
            }
        },
        "/v1/community-tokens/{externalAddressOrViewType}/viewing-sessions/{viewingSessionId}": {
            "get": {
                "description": "Returns community tokens information for a specific viewing session.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"top\"",
                        "description": "View type (top, trending, or bondingCurveProgress)",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"550e8400-e29b-41d4-a716-446655440000\"",
                        "description": "Viewing session ID",
                        "name": "viewingSessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"bitcoin\"",
                        "description": "Search keyword",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 10,
                        "description": "Number of items to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 0,
                        "description": "Number of items to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tokenanalytics.CommunityToken"
                            }
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    }
                ]
            }
        },
        "/v1sse/community-tokens": {
            "get": {
                "description": "Streams community tokens information for the given Ion Connect addresses.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "example": "0x1234...,0x5678...",
                        "description": "External addresses of the tokens",
                        "name": "externalAddresses",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 10,
                        "minimum": 1,
                        "type": "integer",
                        "example": 3,
                        "description": "Number of top holders to include (1-10)",
                        "name": "includeTopHolders",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.CommunityToken"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    }
                ]
            }
        },
        "/v1sse/community-tokens/{externalAddressOrViewType}": {
            "get": {
                "description": "Streams community tokens information for the given type.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"latest\",\"featured\",\"top\",\"trending\",\"bondingCurveProgress\"",
                        "description": "View type (latest, featured, top, trending, or bondingCurveProgress)",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"550e8400-e29b-41d4-a716-446655440000\"",
                        "description": "Viewing session ID (required for top/trending/bondingCurveProgress)",
                        "name": "viewingSessionId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"profile\"",
                        "description": "Token type filter (profile, post, video, or article)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tokenanalytics.CommunityToken"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    }
                ]
            }
        },
        "/v1sse/community-tokens/{externalAddressOrViewType}/latest-trades": {
            "get": {
                "description": "Streams latest trades for a specific community token address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 10,
                        "description": "Number of items to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 0,
                        "description": "Number of items to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.Trade"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    }
                ]
            }
        },
        "/v1sse/community-tokens/{externalAddressOrViewType}/ohlcv": {
            "get": {
                "description": "Streams OHLCV (Open, High, Low, Close, Volume) data for a specific community token address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"1m\"",
                        "description": "Time interval",
                        "name": "interval",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.OHLCV"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    }
                ]
            }
        },
        "/v1sse/community-tokens/{externalAddressOrViewType}/top-holders": {
            "get": {
                "description": "Streams top holders information for a specific community token address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 10,
                        "description": "Number of items to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tokenanalytics.TopHolderPosition"
                            }
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    }
                ]
            }
        },
        "/v1sse/community-tokens/{externalAddressOrViewType}/trading-stats": {
            "get": {
                "description": "Streams trading statistics for a specific community token address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.TradeStats"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    }
                ]
            }
        },
        "/v1ws/community-tokens": {
            "get": {
                "description": "Streams community tokens information for the given Ion Connect addresses.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "example": "0x1234...,0x5678...",
                        "description": "External addresses of the tokens",
                        "name": "externalAddresses",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 10,
                        "minimum": 1,
                        "type": "integer",
                        "example": 3,
                        "description": "Number of top holders to include (1-10)",
                        "name": "includeTopHolders",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.CommunityToken"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    }
                ]
            }
        },
        "/v1ws/community-tokens/{externalAddressOrViewType}": {
            "get": {
                "description": "Streams community tokens information for the given type.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"latest\",\"featured\",\"top\",\"trending\",\"bondingCurveProgress\"",
                        "description": "View type (latest, featured, top, trending, or bondingCurveProgress)",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"550e8400-e29b-41d4-a716-446655440000\"",
                        "description": "Viewing session ID (required for top/trending/bondingCurveProgress)",
                        "name": "viewingSessionId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"profile\"",
                        "description": "Token type filter (profile, post, video, or article)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tokenanalytics.CommunityToken"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    }
                ]
            }
        },
        "/v1ws/community-tokens/{externalAddressOrViewType}/latest-trades": {
            "get": {
                "description": "Streams latest trades for a specific community token address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 10,
                        "description": "Number of items to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 0,
                        "description": "Number of items to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.Trade"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    }
                ]
            }
        },
        "/v1ws/community-tokens/{externalAddressOrViewType}/ohlcv": {
            "get": {
                "description": "Streams OHLCV (Open, High, Low, Close, Volume) data for a specific community token address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"1m\"",
                        "description": "Time interval",
                        "name": "interval",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.OHLCV"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    }
                ]
            }
        },
        "/v1ws/community-tokens/{externalAddressOrViewType}/top-holders": {
            "get": {
                "description": "Streams top holders information for a specific community token address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int32",
                        "example": 10,
                        "description": "Number of items to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tokenanalytics.TopHolderPosition"
                            }
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    }
                ]
            }
        },
        "/v1ws/community-tokens/{externalAddressOrViewType}/trading-stats": {
            "get": {
                "description": "Streams trading statistics for a specific community token address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0x1234...\"",
                        "description": "External address",
                        "name": "externalAddressOrViewType",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenanalytics.TradeStats"
                        }
                    },
                    "401": {
                        "description": "if auth token is missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ResponseErrorBody"
                        }
                    }
                },
                "security": [
                    {
                        "Nostr": []
                    }
                ]
            }
        }
    },
    "definitions": {
        "main.SessionViewCreateResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "ttl": {
                    "description": "Session TTL in seconds",
                    "type": "integer",
                    "example": 1800
                }
            }
        },
        "server.ResponseErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "SOMETHING_NOT_FOUND"
                },
                "error": {
                    "type": "string",
                    "example": "something is missing"
                }
            }
        },
        "tokenanalytics.Addresses": {
            "type": "object",
            "properties": {
                "ionConnect": {
                    "type": "string"
                },
                "twitter": {
                    "type": "string"
                }
            }
        },
        "tokenanalytics.BondingCurveProgress": {
            "type": "object",
            "properties": {
                "currentAmount": {
                    "type": "number"
                },
                "currentAmountUSD": {
                    "type": "number"
                },
                "goalAmount": {
                    "type": "number"
                },
                "goalAmountUSD": {
                    "type": "number"
                }
            }
        },
        "tokenanalytics.CommunityToken": {
            "type": "object",
            "properties": {
                "addresses": {
                    "$ref": "#/definitions/tokenanalytics.Addresses"
                },
                "createdAt": {
                    "type": "string"
                },
                "creator": {
                    "$ref": "#/definitions/tokenanalytics.User"
                },
                "description": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "marketData": {
                    "$ref": "#/definitions/tokenanalytics.MarketData"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "tokenanalytics.HolderPosition": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "amountUSD": {
                    "type": "number"
                },
                "holder": {
                    "$ref": "#/definitions/tokenanalytics.User"
                },
                "rank": {
                    "type": "integer"
                },
                "supplyShare": {
                    "type": "number"
                }
            }
        },
        "tokenanalytics.MarketData": {
            "type": "object",
            "properties": {
                "bondingCurveProgress": {
                    "$ref": "#/definitions/tokenanalytics.BondingCurveProgress"
                },
                "holders": {
                    "type": "integer"
                },
                "marketCap": {
                    "type": "number"
                },
                "position": {
                    "$ref": "#/definitions/tokenanalytics.Position"
                },
                "priceUSD": {
                    "type": "number"
                },
                "ticker": {
                    "type": "string"
                },
                "topHolders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tokenanalytics.HolderPosition"
                    }
                },
                "volume": {
                    "type": "number"
                }
            }
        },
        "tokenanalytics.OHLCV": {
            "type": "object",
            "properties": {
                "close": {
                    "type": "number"
                },
                "high": {
                    "type": "number"
                },
                "low": {
                    "type": "number"
                },
                "open": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "integer"
                },
                "volume": {
                    "type": "number"
                }
            }
        },
        "tokenanalytics.Position": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "amountUSD": {
                    "type": "number"
                },
                "pnl": {
                    "type": "number"
                },
                "pnlPercentage": {
                    "type": "number"
                },
                "rank": {
                    "type": "integer"
                }
            }
        },
        "tokenanalytics.TopHolderPosition": {
            "type": "object",
            "properties": {
                "creator": {
                    "$ref": "#/definitions/tokenanalytics.User"
                },
                "position": {
                    "$ref": "#/definitions/tokenanalytics.HolderPosition"
                }
            }
        },
        "tokenanalytics.Trade": {
            "type": "object",
            "properties": {
                "creator": {
                    "$ref": "#/definitions/tokenanalytics.User"
                },
                "position": {
                    "$ref": "#/definitions/tokenanalytics.TradePosition"
                }
            }
        },
        "tokenanalytics.TradePosition": {
            "type": "object",
            "properties": {
                "addresses": {
                    "$ref": "#/definitions/tokenanalytics.Addresses"
                },
                "amount": {
                    "type": "integer"
                },
                "amountUSD": {
                    "type": "number"
                },
                "balance": {
                    "type": "integer"
                },
                "balanceUSD": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "holder": {
                    "$ref": "#/definitions/tokenanalytics.User"
                },
                "type": {
                    "$ref": "#/definitions/tokenanalytics.TradeType"
                }
            }
        },
        "tokenanalytics.TradeStats": {
            "type": "object",
            "properties": {
                "1h": {
                    "$ref": "#/definitions/tokenanalytics.TradeStatsAggregate"
                },
                "24h": {
                    "$ref": "#/definitions/tokenanalytics.TradeStatsAggregate"
                },
                "5m": {
                    "$ref": "#/definitions/tokenanalytics.TradeStatsAggregate"
                },
                "6h": {
                    "$ref": "#/definitions/tokenanalytics.TradeStatsAggregate"
                }
            }
        },
        "tokenanalytics.TradeStatsAggregate": {
            "type": "object",
            "properties": {
                "buysTotalAmountUSD": {
                    "type": "number"
                },
                "netBuy": {
                    "type": "number"
                },
                "numberOfBuys": {
                    "type": "integer"
                },
                "numberOfSells": {
                    "type": "integer"
                },
                "sellsTotalAmountUSD": {
                    "type": "number"
                },
                "volumeUSD": {
                    "type": "number"
                }
            }
        },
        "tokenanalytics.TradeType": {
            "type": "string",
            "enum": [
                "buy",
                "sell"
            ],
            "x-enum-varnames": [
                "tradeTypeBuy",
                "tradeTypeSell"
            ]
        },
        "tokenanalytics.User": {
            "type": "object",
            "properties": {
                "addresses": {
                    "$ref": "#/definitions/tokenanalytics.Addresses"
                },
                "avatar": {
                    "type": "string"
                },
                "display": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "verified": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "Nostr": {
            "description": "Type \"Nostr\" followed by a space and your Nostr NIP-42 compatible base64-encoded event.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "latest",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"https"},
	Title:            "Token Analytics Service API.",
	Description:      "This service provides analytics data for various tokens.\nURLs starting with /v1/sse return Server-Sent Events (SSE) for real-time updates.\nURLs starting with /v1/ws utilize WebSockets for bidirectional communication.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
